### ISSUE TITLE
Polaris documentation does not list sub-component properties

### ISSUE THREAD

**Issue by jbasko** [Shopify/polaris-react#1030]
Polaris documentation has a lot of goodies, but they remain hidden for those who assume that the documentation without examples would list all the options. Some things are only discovered only if you start to click through the example dropdowns.

For example, `Layout.Section` and `Layout.AnnotatedSection` -- is there a way to list all their properties without going to https://github.com/Shopify/polaris-react/blob/master/src/components/Layout/components/Section/Section.tsx ? Many of these subcomponents I only discovered a week or two after starting with Polaris just because someone had pointed to them in the forums or here on github, but in the documentation you look at the component, look at the properties and you ask - that's it?

**Comment by chloerice** [comment]
Hi @jbasko, thanks for raising this. So far, we've only gotten the [`Stack.Item`](https://polaris.shopify.com/components/structure/stack#section-stack-item) and `ResourceList.Item` documented outside of examples. I'll make an issue that outlines all the subcomponents with public APIs so that folks can start tackling the rest 😃
