### ISSUE TITLE
Tabs Component not working properly on 11.14.0

### ISSUE THREAD

**Issue by kaya-mikail** [Shopify/polaris-react#10337]
## Issue summary

1. "fitted" prop does not work, when Tabs are rendered with actions
2. Console is returning error:
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `Modal`.

**Comment by yurm04** [comment]
I believe this issue was resolved with https://github.com/Shopify/polaris/pull/11266. I tested the `Modal` and `Tabs with actions` stories in the storybook and could no longer replicate the error. The `fitted` prop in `Tabs` also seems to work as expected. Going to close this issue. @kaya-mikail if you continue to experience this issue after updating to the latest version of Polaris, please feel free to reopen.
