### ISSUE TITLE
Open styleguide PR fails when latest version is not ready on npm

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#1066]
# Issue summary

We just did a deploy for version `3.8.0`. Everything went smoothly until the creation of the branch in `polaris-styleguide`. 

This failed as the `npm publish` script had completed however the npm registry had not updated the version. This meant that when running `npx yarn upgrade @shopify/polaris@3.8.0` it failed as it could not find the version. Testing the version now locally there is no problem.
( scroll down to the bottom of this link )
https://shipit.shopify.io/shopify/polaris-react/production/deploys/723859

This would also cause an error if the registry was ever down or experiencing some minor outages.

## Expected behavior

When we update `polaris-react` on the new branch in the `polaris-styleguide` if there are any issues we should pause and try again ( maybe a few times ). After the re-attempts fail it should throw an error as the registry may be having issues.

https://github.com/Shopify/polaris-react/blob/1cf3f2a70b43584a6518898053856b4709e28bbe/scripts/open-styleguide-pr.js#L73-L79

## Actual behavior

If the registry does not have the specified version at the time of update the branch creation fails.

## Steps to reproduce the problem

This is a bit tricky as sometimes the registry will be working fast and other times it might be slow or offline.

---

Also I am happy to do a small PR to catch when the update script fails and try again after a delay. Just want to confirm this is an issue first.

**Comment by kaelig** [comment]
This is a known issue, and we decided not to fix it – see https://github.com/Shopify/polaris-react/issues/917

We may want to tell people what to do when this fails, though.

**Comment by alex-page** [comment]
I will add a log on fail of branch creation with the following:

```
It seems your automatic branch creation for polaris-styleguide failed. This can be due to many reasons. To resolve this follow these steps and replace [release-version] with the version you are publishing:

1. Checkout `polaris-styleguide`
2. Get the latest version of master `git checkout master && git pull`
3. Create a new branch based on the version that failed `git checkout -b update-polaris-v[release-version]`
4. Update `shopify/polaris` by running `npx yarn upgrade @shopify/polaris@[release-version]`
5. Add the changed files to git by running `git add package.json yarn.lock`
6. Commit the changes with `git commit -m "Update @shopify/polaris to [release-version]`
7. Push the changes with `git push origin update-polaris-v[release-version]`
8. Create a new pull request for the branch
```

**Comment by amrocha** [comment]
This has happened twice, and it seems like both times it was because the new version didn't propagate to NPM fast enough. I think we should add a simple retry + backoff to the requests in the PR script, to see if we can't fix these issues.

The script that handles opening the PR in the styleguide is `open-styleguide-pr.js`. Right now we're not retrying any requests, and not handling errors. This means that the script could fail if there's a network hiccup or something like that.

I propose adding a function called something like `makeRequest` that knows to retry its requests a few times before throwing an exception, replacing all the raw requests with this function, and wrapping the main body of the script in a try catch that handles this error by outputting a helpful error message.

@alex-page you said you were interested in handling this, how does this sound to you?
