### ISSUE TITLE
Where is the Documentation for Older Versions? 

### ISSUE THREAD

**Issue by sshaw** [Shopify/polaris-react#11095]
## Issue summary

There are 12 major releases for this library but https://polaris.shopify.com/ only has v12. Where can 11, 10, etc... found?

**Comment by chloerice** [comment]
Hi @sshaw 👋🏽 We only support the current major version on the website. You can view the documentation for the version you are on by running the website locally if you are on v10 or higher. You'd need to checkout the commit for the version release you are on and build and serve it. So for example, if you are on v11.26.0: 

- `git checkout 046894b` (that's the v11.26.0 [commit](https://github.com/Shopify/polaris/releases/tag/%40shopify%2Fpolaris%4011.26.0))
  - You can update the version number at the end of the above commit URL to whatever version you're on to easily navigate to its release notes, which link to the tag commit to the right of the title
<img width="1271" alt="Screenshot 2023-11-02 at 7 56 58 PM" src="https://github.com/Shopify/polaris/assets/18447883/814f8a76-b2c8-4c04-8042-43343be7899b">

- `yarn && yarn build && turbo run dev --filter=polaris.shopify.com`
- It will open a new browser tab/window and navigate you to localhost:3000 when the build is successful
- If you run into an error at the OG image gen step:
  - Try [`yarn cache clean`](https://yarnpkg.com/cli/cache/clean)
  - Then retry `yarn build && turbo run dev --filter=polaris.shopify.com`

You can also try the Wayback Machine, but it's less easy to figure out what exact version you're looking at 😅 The easiest way to do that would be to look at the release notes for the version you are on, and select a snapshot on our around that date. For example, the v12 release happened the first week of October, so to view the most recent v11x.x docs you could select a snapshot from end of September. For example, the last [snapshot](https://github.com/Shopify/polaris/releases/tag/%40shopify%2Fpolaris%4011.19.0) of the components section before v12 came out was from [v11.19.0](https://github.com/Shopify/polaris/releases/tag/%40shopify%2Fpolaris%4011.19.0) because that version released September 14, the snapshot is from September 20, and the next version release was after the snapshot was recorded ([v11.20.0](https://github.com/Shopify/polaris/releases/tag/%40shopify%2Fpolaris%4011.20.0) released September 22).

<img width="1001" alt="Screenshot 2023-11-02 at 8 06 26 PM" src="https://github.com/Shopify/polaris/assets/18447883/0162b553-3bb5-402a-b170-26e832421a88">

**Comment by sshaw** [comment]
Hi, thanks so much for the detailed reply. 

> You can also try the Wayback Machine... 

Yes tried this but many pages don't render correctly

I also tried building storybook for those that have it but ran into an error; did not try to resolve. 

Best option for me has been old docs, e.g., https://github.com/Shopify/polaris/blob/v8.2.0/src/components/Card/README.md. Images are broken but it's good enough.
