### ISSUE TITLE
[Popover] Allow specifying which element should get focus when opening

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#1162]

**Comment by sarahill** [comment]
@dpersing let's talk about this. Accessibility concerns?

**Comment by dpersing** [comment]
Working from this mock up (let me know if there's a newer one, @sarahill!)

![Save popover](https://user-images.githubusercontent.com/1462085/54165368-a127ef00-441d-11e9-9ac8-53a2bee3ffeb.png)

Since the filters that are currently applied are listed before the text input, I'd like to refrain from moving focus directly to the field...unless we want to tie the filters list to the text input programmatically, which feels like overkill. By default we send focus to the popover container, which would allow a screen reader user to read through the tags to verify them before they enter or edit the filter name.

Getting rid of the `X` (which I think came up in discussion at one point) would also help avoid focus management confusion I think, since right now the visual order makes me think the merchant would tab to the `X` before reaching the text input as well.

**Comment by tmlayton** [comment]
This is a `wontfix` for now. The underlying `PopoverOverlay` component already has focus logic built in which shift focus to the first node within a `Popover` when it opens. I think we could consider adding a prop which allows us to pass a node to focus after the `Popover` opens, with the default behavior being what currently happens.

**Comment by tmlayton** [comment]
I update the issue and labels. To allow specifying which child element should get focus, I think we could do something like the following which would override the default behavior:

```jsx
<Popover
  autofocusChild={}
/>
```

**Comment by tmlayton** [comment]
After a bit more exploration, `Popover` takes a `preventAutofocus` prop, which in combination with the `Focus` component wrapping your desired element to focus, this will focus any child element of `Popover` upon activating the popover. For example: 

```jsx
<Popover preventAutofocus>
  <Focus>
    <TextField />
  </Focus>
</Popover>
```
