### ISSUE TITLE
[List filters] [a11y] Accessibility review

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react#1173]

**Comment by ry5n** [comment]
@sarahill Let’s work on a short set of instructions for how to review this in Web, and what Devon should do to test it. Then we can assign to her.

**Comment by dpersing** [comment]
Currently testing on `master` in `web` with the flag on. I'm blocked on testing on Windows at the moment due to a cross-scripting issue, but I can start writing up issues that are more general.

**Comment by ry5n** [comment]
(As discussed outside of GitHub, we’re going to opt for video calls to review this together, rather than putting together instructions.)

**Comment by dpersing** [comment]
Issues have been logged in `web` for items specific to the list filters rollout, and in `polaris-ux` for issues that are specific to existing Polaris components:

- Accordion button state: https://github.com/Shopify/web/issues/11781
- Sheet focus management: https://github.com/Shopify/web/issues/11780
- Monochrome link focus state: https://github.com/Shopify/web/issues/11779 and https://github.com/Shopify/polaris-ux/issues/242
- New tab/external link icon: https://github.com/Shopify/web/issues/11760, related to vhttps://github.com/Shopify/polaris-ux/issues/146

Because of issues with CORS, I haven't been able to test in Windows, so it's possible there are issues that affect assistive tech users on Windows.

**Comment by ry5n** [comment]
@dpersing Do you feel satisfied with the review, enough to consider this closed?

**Comment by dpersing** [comment]
@ry5n Works for me! We can do another pass before the full launch for stragglers.
