### ISSUE TITLE
[List filters] [a11y] Add external link icon to opt-in card

### ISSUE THREAD

**Issue by dpersing** [Shopify/polaris-react#1211]
_From the issue originally created by @selenehinkley:_

Since the privacy policy opens in a new tab, we need to add an external link icon.
![54330255-3d92f280-45d2-11e9-9475-b3dda1fe9c98_png__2544×322_](https://user-images.githubusercontent.com/18617698/54386461-5f8e8280-466f-11e9-8080-05494b485fcf.png)

Edit: This is related to the behavior of the external prop that appears in the link and page components: Shopify/polaris-ux#146

**Comment by ry5n** [comment]
I’d like to tackle this within Polaris React in order to enable the external link icon for general use.

Here’s what I’m thinking:

- Add a [trailing icon](https://polaris-icons.shopify.com/?icon=ExternalSmallMinor&q=exter) to Buttons and Links when the `external` prop is true
- Add “(opens a new window)” to the accessible name of Buttons and Links when `external` is true

**Comment by ry5n** [comment]
Here’s a prototype of the technical approach I’m planning to take: https://codesandbox.io/s/9wymvnyrw?fontsize=14&module=%2FApp.js

**Comment by dpersing** [comment]
This looks fantastic!

**Comment by ry5n** [comment]
This banner is now disabled, but external links will automatically get the “opens in new window” icon/warning thanks to https://github.com/Shopify/polaris-react/pull/1247
