### ISSUE TITLE
Unnecessary border radius when wrapping buttons inside segmented ButtonGroup with Tooltips

### ISSUE THREAD

**Issue by meecrobe** [Shopify/polaris-react#1240]
# Issue summary
Border radius getting applied to buttons inside segmented ButtonGroup when wrapping buttons with Tooltip component.

## Expected behavior
![vadzim2 ~ APO ~ Shopify 2019-03-22 16-23-21](https://user-images.githubusercontent.com/8003440/54826087-17e7a680-4cc0-11e9-8892-9f973152a405.png)

## Actual behavior
![vadzim2 ~ APO ~ Shopify 2019-03-22 16-22-56](https://user-images.githubusercontent.com/8003440/54826095-1b7b2d80-4cc0-11e9-8b55-317c43db6192.png)

## Steps to reproduce the problem

Wrap each button inside ButtonGroup with Tooltip.
Sandbox: https://codesandbox.io/s/k260lyr31v

## Specifications

- Are you using the React components? (Y/N): yes
- Polaris version number: 3.11.0
- Browser: Google Chrome 72.0.3626.119
- Device: iMac (21.5-inch, Late 2012)
- Operating System: macOS Mojave 10.14.3

**Comment by ry5n** [comment]
Thanks for reporting this @meecrobe. This is caused by [the way the border-radius is removed for child buttons](https://github.com/Shopify/polaris-react/blob/049df9d41caae5d507744b3476b6d590b76a28da/src/components/ButtonGroup/ButtonGroup.scss#L52).

Do you have ideas on how this could be made more robust?

I definitely think this should be fixed. However, based on the screenshot you provided, have you considered using text labels for the buttons? That may sidestep the issue, and may also be more understandable for users. (Aside from common controls like Bold, Italic, Underline toggles in a text editor toolbar, icons alone are [often harder to understand than text labels](https://www.nngroup.com/articles/icon-usability/).)

**Comment by clauderic** [comment]
There was a slack discuussion around this recently: https://shopify.slack.com/archives/C8H54T86Q/p1562615295416400

This is also an issue when one of the buttons in a ButtonGroup is the activator of a `Popover`.

Perhaps there could be a hacky short term solution to this until a larger refactor can happen? This is the hacky fix that was implemented for the RichTextEditor component in `web`: https://github.com/Shopify/web/blob/master/app/components/RichTextEditor/components/Toolbar/Toolbar.scss#L14

cc @danrosenthal @BPScott

**Comment by danrosenthal** [comment]
In the linked Slack discussion I recommended implementing a `ConnectedProvider` component which used React context to signal to components that they should render as connected. So `Button` and form elements would listen for this context, and, depending on their position, render the right rounded sides. I am thinking about taking this on in the next Foundations Frideation as a proof of concept.
