### ISSUE TITLE
TextField of type="number" misreports value visually when input is an invalid number

### ISSUE THREAD

**Issue by jamesism** [Shopify/polaris-react#1242]
# Issue summary

When using a `TextField` with `type="number"` the user input is restricted to digits and decimal characters, but the user can enter multiple decimal points. This results in the browser reporting `event.currentTarget.value` as null or empty, since it is no longer a valid number value. However, to the user, the input appears to still contain a value (the string with multiple decimal points), but connected components and all event handlers behave as though the value is empty until the user corrects the input to be a valid number.

Definitely feels like this is more of a weird browser behaviour/React bug than a Polaris one, but maybe we can get in the middle to try to fix the user experience a bit. 

After a bit of testing locally it seems like the best solution might be to detect `type="number"` in the `private handleChange` function, and then just cast the value of `event.valueAsNumber` as  String rather than report `event.value` directly. In the error case this reports back `"NaN"` which doesn't seem desirable on the nose, but I think is preferable to having a misreport vs. what the user can still see in the input. From the user's perspective this has the effect of blanking out the input once the user has input an invalid number value, and the from the developer's perspective they will at least see `"NaN"` and have the option to check for this and action on it.

Another option might be to make the `handleKeyPress` logic a bit smarter to check the existing value of the input and disallow multiple decimal characters. 

## Expected behavior

The input should reset to blank, as the value being reported in app land is now empty. Failing that, the input shouldn't allow multiple decimal points in a number input.

## Actual behavior

The invalid number remains in the input from the user's perspectivee. On code sandbox the input will reset to empty on a `blur`, but this seems to only take effect once. Any subsequent invalid number in the input will remain even after a `blur`. Can't explain that one. 

## Steps to reproduce the problem

1. Create a `TextField` of `type="number"`
2. Enter an invalid number value: `1.22.222` 
3. Observe that the reported value to `onChange` is empty, but the invalid number stays in the input.

![polaris](https://user-images.githubusercontent.com/887305/54884298-85710f80-4e45-11e9-8142-3205904fbdc0.gif)

## Reduced test case

https://codesandbox.io/embed/400n7mm2rw

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.11.0
- Browser: Chrome
- Device: MBP
- Operating System: macOS

**Comment by ry5n** [comment]
This is definitely weird behavior. [MDN even calls it out on their docs page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) as browser weirdness.

We definitely need to provide some feedback when input is invalid. However, I don’t think clearing the input is the most graceful solution. In my testing on polaris.shopify.com, it appears that the field is cleared this way at least some of the time.

It would be less disruptive for the user if we showed an error message on the field when the input is invalid, [as described in the Polaris docs](https://polaris.shopify.com/patterns-and-guides/error-messages#form-validation). Something like this:

<img width="345" alt="Screen Shot 2019-04-01 at 11 43 48 AM" src="https://user-images.githubusercontent.com/804014/55351718-e5823a00-5473-11e9-97ee-c5f44bb48519.png">

It would be nice if this were built into the component, although we’d need to figure out how this would work if there is also a value given to the `error` prop. For some types of numbers, we’d want the validation to be more restrictive (limited to integers, or positive integers), so we’d need to not block that.

**Comment by ry5n** [comment]
The solution to this also depends on our general validation strategy. I’m not as familiar with this part. @tmlayton thoughts?

**Comment by tmlayton** [comment]
Hey @jamesism, thanks for opening the issue. This is an interesting one.

So this is actually a valid number in certain languages: https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html (Italian and Norwegian). W3C specs and browser implementations of input types _should_ take this all into consideration.

If this was an invalid type (or your app considers it invalid), I would still strongly suggest we not do any sanitization or validation of the value prop in the component outside of what we get with browser defaults. For a few reasons: this is an area where our opinions might just be entirely wrong, it is potentially off-spec and could cause future problems, and state is a responsibility validation like this should be handled there.

> the input will reset to empty on a blur, but this seems to only take effect once. Any subsequent invalid number in the input will remain even after a blur. Can't explain that one.

This is because, on first pass the input value is invalid thus the native change event dispatched has a value of `''`. So, until you enter a valid number again which triggers a change event, any subsequent change with invalid numbers will not clear the field because React thinks the value did not change (it is still `''`, so no re-render). You can recreate this in the number field example https://polaris.shopify.com/components/forms/text-field, but for some reason the code sandbox blows up preventing it from working further.
