### ISSUE TITLE
Saved search tabs have an outline on focus

### ISSUE THREAD

**Issue by petereszes** [Shopify/polaris-react#1251]
# Issue summary
Saved search(filter) tabs have an outline when in focus

## Expected behavior
Saved search(filter) tabs should not have an outline in any state

## Actual behavior
https://d.pr/v/qBsPkR

## Steps to reproduce the problem

1. Enable the `better-list-filters-opt-in` `better-list-filters` `new_admin_order_index_route` `enable internal routes` beta features
2. Navigate to Orders > All orders
3. Tap/click (keep it tapped, clicked) one of the tabs

## Specifications

- Browser: Firefox 66.0.1 (64-bit)
- Operating System: macOS Mojave 10.14.3 (18D109)

**Comment by ry5n** [comment]
Thanks for taking the time out to log this @petereszes.

You’re right that this doesn’t feel well-crafted. We tend to suppress focus outlines when clicking on an element with the mouse (in buttons for example). However, for people using the keyboard to navigate, we do need an indicator for focus.

What I’d like to do to resolve this is to make some changes to the Tabs component so that:

1) The focus ring is suppressed when clicking on the element with a mouse
2) Change the styling for the focus ring so it’s more consistent with the rest of Polaris. I don’t think we can use the standard focus [interaction state](https://polaris.shopify.com/design/interaction-states) since it looks a lot like the style used for the active tab. I’m thinking of re-using the focus ring we have for text fields.
