### ISSUE TITLE
[Modal] "All examples" StoryBook example seems broken

### ISSUE THREAD

**Issue by beefchimi** [Shopify/polaris-react#1307]
Strange behaviour when running StoryBook locally on the latest master:

<img width="1637" alt="Screen Shot 2019-04-11 at 3 52 12 PM" src="https://user-images.githubusercontent.com/643944/55988450-e71ce080-5c71-11e9-9359-b6c04254d920.png">

**Comment by BPScott** [comment]
The modals examples are setup to be expanded by default - otherwise when we screenshot them for visual regression testing you get an empty page with a button that says "open" which isn't particularly useful. That has the unfortunate side effect of the "All Examples" modal page looking like a hot mess as all the models are open at the same time.

It's not a great behaviour but it is desired to make the individual examples be useful. We could just not render the all examples page for Modals to avoid this confusion. What do you think?

**Comment by ry5n** [comment]
@BPScott That makes sense—hiding the All Examples seems like a good step, especially if it’s easy.

Do the console errors in Curtis’s screenshot seem like an issue?

**Comment by BPScott** [comment]
> Do the console errors in Curtis’s screenshot seem like an issue?

Sometimes the code we write in our examples isn't totally exemplary. In this case it's the code in the "Modal with scroll listener" doing a loop without adding a `key`. It's a little annoying but trivial to fix.
