### ISSUE TITLE
[List filters] On mobile, typing in the text field in the Save filters popover closes the popover when keyboard opens

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react#1360]
# Issue summary

On mobile, typing in the text field inside of the Save filters popover closes the popover when the keyboard opens. This is happening on both Android and iOS devices.

@senecabrandi found this issue when using list filters on his mobile device. (iPhone 7)

- [Video demo](https://d.pr/v/7s7vt9)

## Steps to reproduce the problem

1. Navigate to the Orders list view from your Shopify store on a mobile device
2. Click on a saved filter tab (ex. Open)
3. Click `Saved`
3. Focus the TextField component and type a letter

## Specifications

- Are you using the React components? (Y/N): Yes
- Browser: Chrome 73.0.3683.90, Safari
- Device: Pixel 3, iPhone7
- Operating System: Android 9, iOS 12.2

**Comment by tmlayton** [comment]
I think we can update this issue, as it appears to be with the popover in Polaris itself:

<img src="https://user-images.githubusercontent.com/344839/56769587-7c39d200-6766-11e9-8ae3-dba3d9f5b835.GIF" width="200" />

This appears to be caused by the keyboard opening and scrolling of the viewport which triggers `handleScrollOut` and closes the popover

<img width="1824" alt="Screen Shot 2019-04-25 at 2 32 02 PM" src="https://user-images.githubusercontent.com/344839/56769831-40533c80-6767-11e9-99cf-aded664b59d8.png">

**Comment by tmlayton** [comment]
Went ahead and opened a separate issue: #1367
