### ISSUE TITLE
[Page header] Secondary actions no longer roll up

### ISSUE THREAD

**Issue by ry5n** [Shopify/polaris-react#1660]
## Issue summary

Originally, secondary actions on the Page header would roll up based on the available space into a “More actions” menu.

Last year we made some changes to roll all secondary actins into ellipsis menu to make more room on phones. However, I think something got lost in translation because the rollup on medium size screens no longer works:

![Rollup fail](https://user-images.githubusercontent.com/643944/59296752-b4cd3680-8c54-11e9-99c9-afa26d206305.png)

## Expected

Secondary actions should roll up based on available space, and then transition to a single ellipsis menu on phone-sized screens.

**Comment by beefchimi** [comment]
Just to suggest the ideal path forward:

Once the [`Menu`](https://github.com/Shopify/polaris-react/pull/1653) PR ships, we can pursue a PR to both move `RollupActions` up into the root `components` folder, while at the same time implementing logic to measure the available width in the "menu". We can then "roll up actions" once the available width is filled, as opposed to a `matchMedia` query.

Beyond that, we can swap over any other instances of "roll up" behaviour to use the new component.

**Comment by dpersing** [comment]
@ry5n and @beefchimi, can this issue move forward now that PR #1653 is merged?

**Comment by ry5n** [comment]
I’m not sure—Curtis?

**Comment by beefchimi** [comment]
Yep - it definitely can. However, whether or not that is what the Polaris team _wants to do_ is still to be determined. It could be argued that the consumer should be the one to decide when to pass `true` to the `rollup` prop. I don't have a strong opinion on this at the moment, since we have solved for our needs in the online store UI. I might return to this at some point with a stronger opinion.
