### ISSUE TITLE
Unable to customize empty state for ResourceList

### ISSUE THREAD

**Issue by francescomalatesta** [Shopify/polaris-react#1704]
## Issue summary

Hi, I am working with the ResourceList component and I am trying to customize its empty state in case of no items found.

I am stuck with the default empty state:

![Screenshot from 2019-06-18 21-48-24](https://user-images.githubusercontent.com/1940952/59714996-30aa1e80-9213-11e9-9cd3-464f76e42315.png)

Is there any way to customize it? I checked the documentation and the open/closed issues here, but nothing relevant :(

Thanks for your great work on Polaris. I love it.

**Comment by dpersing** [comment]
Hi @francescomalatesta! Can you share a bit about how you're looking to change the empty state?

**Comment by francescomalatesta** [comment]
Hey @dpersing :) thanks for your quick answer! Honestly I think that the best thing would be give the developer a way to inject another component for the empty state.

Let's say I have my `ResourceList.FilterControl` like the one in the docs. I would add a prop like "noResults" to inject my own component.

Something like:

```
const filterControl = (
      <ResourceList.FilterControl
        noSearchResults={<div>No results for your search criteria!</div>}
        filters={filters}
        appliedFilters={this.state.appliedFilters}
        onFiltersChange={this.handleFiltersChange}
        searchValue={this.state.searchValue}
        onSearchChange={this.handleSearchChange}
        additionalAction={{
          content: 'Save',
          onAction: () => console.log('New filter saved'),
        }}
      />
    );
```

This example is quite simplistic but the point is that I actually have no control on the output at all :(

I am quite new to react, maybe I am missing something, thanks for your feedback :)

**Comment by asalisbury** [comment]
I believe there is also a valid scenario where the existing empty state (with the search icon and copy that says, "Try changing the filters or search term") is misleading to users.

For instance, say the initial state of a resource (e.g., Products) has zero items:

<img width="1079" alt="Screen Shot 2019-07-25 at 1 51 25 PM" src="https://user-images.githubusercontent.com/916549/61896592-50ec8d80-aee3-11e9-8fe7-6a77e10f0d8a.png">

The empty state shown in this case is not helpful, because the user does not change their filters/search query, but rather, they need to create a new product. 

Related: https://github.com/Shopify/polaris-react/issues/1120

cc: @annemarieleger
