### ISSUE TITLE
[Autocomplete] - Design exploration

### ISSUE THREAD

**Issue by dleroux** [Shopify/polaris-react#1793]
General ticket for the design exploration of the new AutoComplete component.

**Comment by sarahill** [comment]
The **BOP** (Back office platform) team held a workshop last Wednesday, July 17th.

**Workshop goal**
The goal of the workshop was for the team to align on the goal of an autocomplete and come up with a general direction to take further.

**TL;DR**
We had a good general discussion about the definition of autocomplete and how/if it defers from autocomplete within a search experience. From this discussion, we came up with a long-term goal of: _Guide people in completing entries quickly and accurately_. The overall takeaway from the discussion and sketching exercises is we want to design a simple yet flexible component and provide guidance to the consumer that gives them clarity on to customize it for their context.

**Summary and outcomes of the workshop:**
https://pasteapp.com/p/syN4Q7BtpXN?view=Y8wF5kYKTcx

**Jamboard, all workshop exercises:**
https://jamboard.google.com/d/16yzZ7WwWop81bmKPF5dGtomR6b38-GR6hgjyRgye3bc/viewer

**Comment by sarahill** [comment]
# Review 1: Dan L. and Devon
September 17, 2019

## Goal

Go over flows/ideas for autocomplete and decide as a group on directions to continue to explore and flesh out further.

## In page

The autocomplete is triggered by a text field on the page. An example of this is the add tags field on the product details page.

Because of embedded apps:
keep the modal/sheet below the top bar. keep experience the same

Touch base with the App bridge team. they could fix this and make it work fullscreen

Single or multi-select
prop to allow for multi

Keep the “Done” button for both cases: single and multi-select. Helps confirm the merchant is done with the activity.# Review 1: Dan L. and Devon
September 17, 2019

![image](https://user-images.githubusercontent.com/8629173/65075210-74bcd480-d964-11e9-87a2-47e6e5bc7096.png)

## In sheet

The autocomplete is triggered by a text field that is already in a sheet. An example of this is the tag field in the More filters sheet.

use the sheet autocomplete interaction on desktop and mobile

transition on the desktop:
slide from the right instead of the bottom?

if the field is triggered from the page, it will be a popover on desktop

“creatable” instead of before/after action
• end of the list if other suggestions
• only option if no others

empty state along with “add” option

![Screen Shot 2019-09-17 at 3 44](https://user-images.githubusercontent.com/8629173/65075252-91590c80-d964-11e9-90bf-1f4a3d4a917b.png)

## In popover

The autocomplete is triggered by a text field that is in a popover. An example of this is the location switcher on the Orders list page.

Option 1

This could function more as the modal/sheet does where the location picker fills the page, make a selection, picker closes.

Option 2

Popover gets pinned under the top bar allowing for more keyboard and scrolling space.

![IMG_20190917_094740](https://user-images.githubusercontent.com/8629173/65075290-a59d0980-d964-11e9-97b3-0ea55220ff0c.png)

## In modal

The autocomplete is triggered by a text field that is in a modal. An example of this is filtering in Reports.

This needs a little more exploration but the direction explored currently is similar to some of the above. The field takes over the modal so that the autocomplete is the primary action.

![IMG_20190917_104708](https://user-images.githubusercontent.com/8629173/65075335-b9e10680-d964-11e9-98d0-04d645209db5.png)

## Next steps

- Push the designs further
- Clean up interactions
- Add empty states
- Mock up both single-select and multi-select flows for each scenario
- Work with Sadie through explorations

**Comment by sarahill** [comment]
Paired with Sadie today. We went over the review from yesterday with Devon and Dan, went through the single select flow and came up with questions and tasks for us to tackle.

- [ ] **Initial state and Empty state**
    Should these be different? Do we need an initial state?
- [ ] **Let people know if they can select one or more than one option**
    Do we need this for single and multi-select?
- [ ] **Error handling**
    Creation - Option already exists
- [ ] **Design interaction states**

---

When selecting a product type or vendor, the fields have a `connectedRight` button that triggers the list of options when clicked. This is an alternative to the list opening when the field is focused. 

Are there other ways we can handle this on mobile? maybe “show more options” instead of select arrows? could show more options incrementally, could keep clicking. performance issues? talk to products team

May not be something we want to have control over.

![image](https://user-images.githubusercontent.com/8629173/65175699-5e288300-da21-11e9-8d21-b43716b8ce29.png)

**Comment by dpersing** [comment]
A book excerpt on accessible autocomplete patterns: https://adamsilver.io/articles/building-an-accessible-autocomplete-control/
