### ISSUE TITLE
Build fails due to an wrong import

### ISSUE THREAD

**Issue by joba-sprd** [Shopify/polaris-react#1818]
## Issue summary

When i try to build my project with version 3.19.0 i get the following typescript error:
```
ERROR in [at-loader] ./node_modules/@shopify/polaris/types/components/Filters/Filters.d.ts:1:8  
TS1259: Module '"xxx/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
```

I guess its related to the import of react in the Filters.d.ts.
`import React from 'react';` should be `import * as React from 'react';` like in the other type definition files. 

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.19.0
- Device: MacBook Pro (Retina, 15', Mid 2015)
- Operating System: MacOS 10.14.5
- Package Manager: Yarn

**Comment by BPScott** [comment]
Thanks for the issue @joba-sprd. We'll fix this in #1820 for version 3.

As a heads up, we're going to be moving to the `import React` syntax for all components in v4. In order to have this continue to work in your project you should set `esModuleInterop` to true in your typescript options. The [typescript team recommends setting esModuleInterop](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop) for all projects, and it's only a flag for backwards compatibility reasons.
