### ISSUE TITLE
The DropZone `overlayText` and `overlay` props appear to have no effect.

### ISSUE THREAD

**Issue by jeffblake** [Shopify/polaris-react#1896]
This can be reproduced on the documentation page: https://polaris.shopify.com/components/actions/drop-zone#navigation

I was expecting the text to appear somewhere when I hover over the drop zone.

**Comment by chloerice** [comment]
Hey @jeffblake, sorry for the confusion. The prop description should say on drag instead of on hover. The `overlay` and `overlayText` on `Dropzone` are rendered when you drag something over the drop zone.

 
![2019-07-30 14 41 19](https://user-images.githubusercontent.com/18447883/62156008-2b42f800-b2d8-11e9-84c5-0c81b8dfc033.gif)

I'll update the prop description for better clarity!

**Comment by jeffblake** [comment]
Ah, gotcha. Thanks.
