### ISSUE TITLE
[Filters] additional actions for filters

### ISSUE THREAD

**Issue by sijad** [Shopify/polaris-react#1951]
## Feature request summary

currently it's not possible to add additional actions to `Filters` component like what [FilterControl](https://github.com/Shopify/polaris-react/blob/7e4e9e88007303782a8022b60224e4f9dd8d5cd0/src/components/ResourceList/components/FilterControl/FilterControl.tsx#L19) has.
I basically need it for letting user save their filters but if it's not what `Filters` is intended for, docs should clarify it when `FilterControl` should be used instead of `Filters`?

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by AndrewMusgrave** [comment]
Hi, @sijad from my understand `Filters` is always intended over `FilterControl` however @danrosenthal worked on the project and speak towards this.

**Comment by danrosenthal** [comment]
That's right @AndrewMusgrave, `Filters` are the blessed path going forward. We'll likely deprecated with the intent to remove `FilterControl`.

**Comment by yourpalsonja** [comment]
Closed by #1774!

@tmlayton has a bit more context for you and might be able to help answer your question!

**Comment by tmlayton** [comment]
Hey @sijad, as @yourpalsonja mentioned the docs will be clarified in #1774. We are deprecating `FilterControl` and it will be removed entirely in v5. `Filters` is replaces `FilterControl` entirely. 

For the `Filters` component, instead of `additionalAction`, it takes `children` which get rendered inline with `Filters` and is how we render our save button in Shopify (take a look at `/admin/orders` if you have a shop). I will add an example for this in the `Filters` docs as part of #1774.
