### ISSUE TITLE
Implement Frame in Next.js

### ISSUE THREAD

**Issue by sgtpsibin** [Shopify/polaris-react#1999]
Hello all,
Anyone have a boilerplate/example with full frame implements (Navigation,TopBar)? I am having a problem with Navigation...:( Please help me.
Please build a fully working example of Navigation with react-router in a CodeSandbox and link to it in the docs.

**Comment by sgtpsibin** [comment]
i have a problem with prop 'url' in Navigation.Section. When i click on a navigation item...this is http request and the page reload...it not like route in Next.js

**Comment by BPScott** [comment]
Hi @sgtpsibin 

It sounds like the one piece you're missing is passing a `linkComponent` prop into AppProvider to allow you to override our links, so that instead of rendering a plain `<a>` tag it renders a react-router `Link`. See the 'with linkComponent` example on https://polaris.shopify.com/components/structure/app-provider for more details.


[You can see an example of this in our polaris-icons app](https://github.com/Shopify/polaris-icons/blob/master/packages/app-icon-explorer/src/components/AppFrame/AppFrame.tsx). That was built with gatsby (and thus react-router) but the principle would remain the same.

**Comment by sgtpsibin** [comment]
@BPScott  i got it....thank you soooo muchhhhhhhh

**Comment by JorgeCeja** [comment]
@sgtpsibin @BPScott are there any repository or code snippets on how to implement Frame with Nextjs? 

There seem to be trade-offs with each take. My main issue for the Frame to not re-render when changing routes/pages.

**Comment by BPScott** [comment]
https://polaris.shopify.com/components/structure/app-provider#section-using-linkcomponent provides an example of how to use AppProvider's linkComponent so that you can swap out the default links - "<a>" tags which will cause rerendering - for the link component of react-router. I'm not familar enough with next.js's router to demonstrate how to do that in next, but the approach will likely be very similar.
