### ISSUE TITLE
Redux with polaris

### ISSUE THREAD

**Issue by sajan1231** [Shopify/polaris-react#2074]
Hi
I am new to react and this Polaris library so i want to know that how can i use redux and react routs with Polaris or any other state management tool ? And what is the flow of Polaris library ?

**Comment by chloerice** [comment]
Hey @sajan1231, `@shopify/polaris` is a React component library. You can use the components in your Shopify apps just like you would with your own React components or the components from other libraries. You just need to be sure to wrap the highest level of your app with the [`AppProvider`](https://polaris.shopify.com/components/structure/app-provider) component so the Polaris React components have access to the context they need.

How you decide to manage the state or routing of your app is up to you. Apps using Polaris React don't have to use a certain stack or set of libraries in order to work (other than React). 

It's structure and API usage are outdated now that `react-router` and `apollo` etc have changed so much, but here's the repo for an example app we built for an [introductory Polaris React workshop](https://github.com/Shopify/product-reviews-polaris-example/blob/master/workshop.md) last year that has routing.

**Comment by sajan1231** [comment]
Thank you very much.
