### ISSUE TITLE
[ResourceItem] Performance issue on shouldComponentUpdate

### ISSUE THREAD

**Issue by posth** [Shopify/polaris-react#2164]
## Issue summary

When using the `<ResourceList />` component, and passing a custom child component to the `<ResourceList.Item />` that has a loading state attached to an API call, `shouldComponentUpdate` does some [deep comparisons on the props](https://github.com/Shopify/polaris-react/blob/master/src/components/ResourceItem/ResourceItem.tsx#L124) to determine if the item should re-render, which causes a blocking of the rendering of the page for very long periods of time for the specific use-case.

## Expected behavior

`shouldComponentUpdate` optimizes its comparison of possible complex child components.

Deep comparisons in `shouldComponentUpdate` aren't ideal, see [related issue](https://github.com/facebook/react/issues/11107)

#### Use-case example 

This was found in the Shopify `web` admin, blocking for **13 seconds** in this example - locally this comparison is much faster, but still observable.

| Performance profile example of the use-case in production  |
|---|
| ![deepComparisonProduction](https://user-images.githubusercontent.com/5506721/65170993-e2760880-da17-11e9-9d12-846e4fd88e3a.gif) |

| `isEqual` starts to go very deep in React `FiberNode`s |
|---|
| ![propsDeepComparison](https://user-images.githubusercontent.com/5506721/65171266-72b44d80-da18-11e9-9e93-d77119d2eb68.png)|

## Steps to reproduce the problem

This is difficult because the lag is only very noticeable on the production code of Shopify `web`.

However, here's a sandbox that tries to mimic the same behavior:

https://codesandbox.io/embed/festive-oskar-xq5xz?fontsize=14

| The performance profile of that sandbox looking at the `isEqual` check  |
|---|
| <img width="1903" alt="Screen Shot 2019-09-18 at 2 33 24 PM" src="https://user-images.githubusercontent.com/5506721/65175910-c1b2b080-da21-11e9-9ac8-5c086b13033f.png">|

Related issue for Shopify admin `web` is https://github.com/Shopify/store/issues/9546

Removing this props deep equal check from the Shopify web production build resolves this issue.

## Specifications

```bash

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 125.98 MB / 16.00 GB
    Shell: Unknown
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
    Safari: 12.1.1
  npmPackages:
    react: ^16.8.6 => 16.8.6
    react-dom: ^16.8.6 => 16.8.6

```

**Comment by ltakens** [comment]
I experience a similar issue. Although on my low-end laptop the browser tab just freezes.
Context: I am trying to resort a ResourceList in which the ResourceItems have an Avatar media component.

This seems to happen: 
From [here](https://github.com/Shopify/polaris-react/blob/master/src/components/ResourceItem/ResourceItem.tsx#L126) the props for the resourceitem are compared to the nextProps. The props object for resourceitem has a key called media. In my case the media value holds a property '_owner' that points to a FiberNode. That FiberNode has a property 'return' that points to another FiberNode, whose return property points to another FiberNode... and so on. The lodash comparison functions recursively compare all those. As it says in their [code](https://github.com/lodash/lodash/blob/4.17.15-npm/_equalObjects.js#L62), this may be "susceptible to call stack limits".

If I set the media property of the resourceitem to null, the resourcelsit rerenders without issues.
![Beginning- of-callstack](https://user-images.githubusercontent.com/12794611/70141888-4794de00-1698-11ea-91a0-667247e1da6d.png)

**Comment by robin-drexler** [comment]
Stumbled upon this again and judging by https://github.com/redux-form/redux-form/issues/3461#issuecomment-334411785, comparing react elements appears to discouraged and we're not the only ones having issues with doing so.

However, there's https://www.npmjs.com/package/react-fast-compare (by formidable labs), which seems to work with react components as well. 

I'd suggest that we either use that library in place of `isEqual` from `lodash` or remove the children comparisons from polaris.

**Comment by robin-drexler** [comment]
it seems like the current `shouldComponentUpdate` implementation in the `ResourceItem` always returns `true` because lodash `isEqual` always seems to return `false` for the children comparison.
https://codesandbox.io/s/condescending-shannon-85fbz

I tried the exact same example with react-fast-compare where it worked. 🎉

**Comment by avocadomayo** [comment]
Hi team, I'm having an issue with this exact problem in prod.

I have a component called [RecentActivitiesList](https://github.com/Shopify/web/blob/master/app/sections/Marketing/MarketingOverview/components/RecentActivitiesList/RecentActivitiesList.tsx) that utilizes `ResourceItem` in a [child component](https://github.com/Shopify/web/blob/master/app/sections/Marketing/components/ActivityListItem/ActivityListItem.tsx). 

Locally, there are no freezing issues. However the freezing problem caused by the issue in `shouldComponentUpdate` is serious in prod- it blocks the rendering thread for several minutes (see an example profile below)
![image (1)](https://user-images.githubusercontent.com/8923697/79373228-5338c100-7f24-11ea-822c-c8a2e38c08cb.png)
)

We have used `ResourceItem` in the past without any issues- this is the first time I'm observing this issue. Does anyone have any tips on reproducing this locally? Or any insight into getting around this problem? 🙏

**Comment by jineshshah36** [comment]
Hi, I wanted to post this here as well as I'm not sure if closed pull requests are watched:

Hi, we merged this change it broke a bunch of our ResourceItem components. I have put together a codesandbox here which exemplifies the problem.

Essentially, if you attempt to update the children of the resource item asynchronously without making any additional prop changes, it will never re-render. In the example I included, the author is "fetched" asynchronously, and when we attempt to re-render with the author info, it doesn't.

I believe excluding children is simply a cure for the symptom, but the real problem is that the code is using deep equals instead of shallow equals. Is there a reason for the deep equals? Shouldn't all props be immutable, therefore not need a deep equals comparison? It seems like you could solve all problems by just doing a shallow equals across all props? I would argue that if you need deep equals, it would imply that some of your props are not immutable.
