### ISSUE TITLE
Stepper component is documented but doesn't actually exist

### ISSUE THREAD

**Issue by josharmitage** [Shopify/polaris-react#2274]
## Issue summary

There is some partially-written documentation for a Stepper component, but the component itself doesn't exist - there are no component code/styles in the repo.

## Expected behavior

The component should exist and be usable and the props should be listed.

## Actual behavior

The component doesn't exist and documentation is incomplete.

## Steps to reproduce the problem

https://polaris.shopify.com/components/forms/stepper
https://github.com/Shopify/polaris-react/tree/master/src/components/Stepper

**Comment by dleroux** [comment]
Hi @josharmitage, thanks for bringing this up! We don't actually have a stepper component in polaris-react because on the web you can simply use the `Textfield` with a `type` of number and you'll get a stepper. See this [codesandbox](https://codesandbox.io/embed/hopeful-lake-gv8oh). You could also use `connectedRight` and`connectedLeft` to create a stepper. See [here](https://codesandbox.io/embed/condescending-sun-6jqhw). 

The example you linked to is for Android and iOS because those do exist. I'll leave this issue open so that we can use it to document this as it can see how it can be confusing.

**Comment by josharmitage** [comment]
Hi @dleroux, thanks for the reply! I was unaware you could change `TextField` type to number. I've taken your suggestion and used that along with `connectedRight`/`connectedLeft`. 👍
