### ISSUE TITLE
[DatePicker] Date normalization appears to break date range selection

### ISSUE THREAD

**Issue by debchn** [Shopify/polaris-react#2481]
## Issue summary

Normalizing the "end" date to represent the end of that day appears to break date selection. It only becomes possible to select _one_ date, instead of a range.

cc @amrocha 

## Expected behavior

I expect the date picker to continue to function as usual— pass the range of dates I have clicked on to `onChange`.

## Actual behavior

<details>
      <summary>It becomes impossible to select a range of dates, see GIF:</summary>
      <img src="http://g.recordit.co/B8qoC3T5VJ.gif" alt="Failed attempts to select a range">
    </details>

## Steps to reproduce the problem

1. Set up a `<DatePicker />` with `multiMonth` and `allowRange` enabled. Use the example in [Polaris docs](https://polaris.shopify.com/components/forms/date-picker)
1. Update the `onChange` handler to set a different `Date` in state than the one passed in. I used a new "end" value that represents the end of the day.

## Reduced test case

https://codesandbox.io/s/shopify-polaris-react-typescript-playground-x13i1?fontsize=14&hidenavigation=1&theme=dark

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.4.0 (and also whatever is in the code sandbox ^)
- Browser: Chrome
- Device: MacBookPro
- Operating System: Catalina

**Comment by jacquesporveau** [comment]
I'm going to start working on this.

**Comment by jacquesporveau** [comment]
An observation just incase I don't end up being able to fix this one.

In the reproduced test case in the issue description you will notice that Feb. 6th is initially selected. Initially you can select another day in the future (Feb. 28th) to create a range but after you've taken action once you cannot create a range again.

**Comment by jacquesporveau** [comment]
Alright so I think I've narrowed this one down and it looks to be a quirk in the way the function `getNewRange` from `@shopify/javascript-utilities/dates'` works.

```ts
  const firstDate = {
    start: new Date(
      'Thu Feb 01 2018 00:00:00 GMT-0800 (Pacific Standard Time)',
    ),
    end: new Date('Thu Feb 01 2018 23:59:59 GMT-0800 (Pacific Standard Time)'),
  };

  const secondDate = new Date(
    'Wed Feb 28 2018 00:00:00 GMT-0800 (Pacific Standard Time)',
  );

  console.log(getNewRange(firstDate, secondDate));
  => { start: 2018-02-28T08:00:00.000Z, end: 2018-02-28T08:00:00.000Z }

  const thirdDate = {
    start: new Date(
      'Thu Feb 01 2018 00:00:00 GMT-0800 (Pacific Standard Time)',
    ),
    end: new Date('Thu Feb 01 2018 00:00:00 GMT-0800 (Pacific Standard Time)'),
  };

  const forthDate = new Date(
    'Wed Feb 28 2018 00:00:00 GMT-0800 (Pacific Standard Time)',
  );

  console.log(getNewRange(thirdDate, forthDate));
  => { start: 2018-02-01T08:00:00.000Z, end: 2018-02-28T08:00:00.000Z }
```

Basically it looks like if the start and end date are not the exact some point in time in the object passed in as the first argument to `getNewRange` then it assumes that you've already selected a range of "Days" and it should return a singular day as the new range because the function thinks you are trying to select a new start date.

Pretty confusing I know haha.

Anyways I think the offending code is the `getNewRange` behaving quirky: 

https://github.com/Shopify/polaris-react/blob/master/src/components/DatePicker/components/Month/Month.tsx#L93

Here is the code to search for just incase line 93 gets changed soon.

```tsx
  const handleDateClick = useCallback(
    (selectedDate: Date) => {
      onChange(getNewRange(allowRange ? selected : undefined, selectedDate));
    },
    [allowRange, onChange, selected],
  );
```

I don't think this ticket is really actionable at this point because as far as I know the date util library isn't open source but I would recommend filing a ticket with that project.
