### ISSUE TITLE
RangeSilder submits a form automatically on a value change

### ISSUE THREAD

**Issue by gerwinbrunner** [Shopify/polaris-react#2588]
## Issue summary

When a RangeSlider is placed in a <from> then the change of a slider triggers the form to automatically submit

## Expected behavior

A change of a RangeSilder value should NOT submit the form automatically

## Steps to reproduce the problem

1. open 
https://codesandbox.io/embed/elastic-roentgen-xv8hi?fontsize=14&hidenavigation=1&theme=dark
1. open the console
1. change a value and see the console log of the form submit

## Reduced test case

https://codesandbox.io/embed/elastic-roentgen-xv8hi?fontsize=14&hidenavigation=1&theme=dark
## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:  4.10.2 
- Browser: Chrome
- Device: Macbook + iPhone
- Operating System: macOS + iOS

**Comment by braccolucianoj** [comment]
# Issue summary 
I have the same issue. I won't add all the issue's fields because are the same as the previous one)

# Extra information
- When adding a wrapper (HTML element) outisde the RangeSilder and adding a click event handler which prevents the default behaviour: the form doens't submit itself but the range slider buttons behave weird.

# Specifications
- Polaris version number: 4.10.2
- Browser: Chrome
- Device: lenovo-V330-15IKB
- Operating System: linux (ubuntu)
