### ISSUE TITLE
[Feature request] Resource picker (non-embedded)

### ISSUE THREAD

**Issue by ptcampbell** [Shopify/polaris-react#2632]
## Feature request summary

In my view, the embedded Resource Picker is the most valuable component from the perspective of an embedded app developer. It provides a native feeling experience and saves us rebuilding a core piece of functionality that would be otherwise tedious to rebuild if you consider how much goes into it (pagination, API calls, variants, multiple types of resources etc.) 

In addition, there are other scenarios (non-modal experiences) where a resource picker would be useful. Such as a popover, or on a page. 

## Rationale

The ResourcePicker exists in the AppBridge but if I am honest 90% of my own bugs have something to do with this weird iframe experience —  the latest cookie / params complications have probably pushed me over the edge, and into the "not worth it" basket. The amount of issues here stemming from embedded experiences is an indicator of that. 

## Sidebar

If this idea is a non-starter I'd love to hear how I might tackle jerry-rigging the existing ResourcePicker to work outside of the AppBridge.

**Comment by srameshr** [comment]
Yes, this is the most important feature we would ever want. Our whole app is embedded because we dont want to build this feature.

**Comment by BPScott** [comment]
The short answer is: this isn't going to happen. 

The Resource Picker in app-bridge makes calls to the parent frame which does a lot of data heavy lifting. If you're not an embedded app then you can't use that mechanism for getting data. You need to authenticate and make data calls to Shopify's graphql API.

polaris-react is a UI component library. It deliberately avoids having any opinion on how to do things like data fetching, as we assume you've got your own opinions on what tool you want to use for that. We don't want to try and make assumptions about such data fetching requirements as they'll probably end up being different to your existing preferred solutions. 

The worst case scenario is we use something different to what you're already using and then you app ends up being bloated because of multiple dependencies that do broadly the same thing - which is bad for your users. 
The best case case scenario is we use the same thing as what you happened to be already using for data fetching and then you'll have to configure data providers twice - once for your own app and once for polaris components that fetch data. At which point you'll say hey this is kinda weird, can polaris-react be our source of truth for data fetching and then our scope massively balloons as we need to start having opinions on the best ways to handle data. Which is still pretty rubbish.


The [Shopify app tutorial](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/learn-the-graphql-admin-api) has a section on how to connect to our graphql API.
