### ISSUE TITLE
TabMeasurer tests fail in React >=16.10

### ISSUE THREAD

**Issue by BPScott** [Shopify/polaris-react#2694]
## Issue summary

TabMeasurer tests fail in React >=16.10.

I don't know what this means for actual behaviour of the Tabs.

My gut is saying that https://github.com/Shopify/polaris-react/blob/master/src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx#L67-L69 has something to do with this but I haven't dove into it

## Expected behavior

Test pass

## Actual behavior

Tests fail

## Steps to reproduce the problem

1. Update `react` and `react-dom` to be `16.10.2` in package.json and do a yarn install
2. Run `yarn run test`
3. Pull a funny face

Ping @AndrewMusgrave / @chloerice / @dleroux

**Comment by AlanSwenson** [comment]
I believe what happens when this fails is is that when the tabs render, the open tap is full width and then other tabs are collapsed instead of having regular width tabs.   
in 16.12
![Screen Shot 2020-02-01 at 12 46 32 PM](https://user-images.githubusercontent.com/4286252/73597549-b359c280-44f2-11ea-8063-00cbc1478148.png)
in 16.9
![Screen Shot 2020-02-01 at 12 59 09 PM](https://user-images.githubusercontent.com/4286252/73597551-bb196700-44f2-11ea-8068-83dde3d3c26c.png)
