### ISSUE TITLE
Tabs loading inconsistently with SSR application

### ISSUE THREAD

**Issue by djoksimo** [Shopify/polaris-react#2706]
## Issue summary

This issue appears in an internal SSR application.

The tabs load in small-device/collapsed view when I refresh the page, but the tabs load as expected when I navigate to the page via a button/link.

#### From Reload:
![image](https://user-images.githubusercontent.com/32694765/73692568-9106a700-46a2-11ea-85c2-3d69f0f46fc9.png)

#### From url/path navigation to the page that contains these tabs:
![image](https://user-images.githubusercontent.com/32694765/73692588-995ee200-46a2-11ea-9a67-b2f17c588eeb.png)

Issue appears with both React v16.9.0 and v16.12.0. I tried using both query parameters, and useState to manage the `selected` tab index but neither approaches solved this issue.

Using fitted tabs does not fix this issue either.

It seems that the bug does not appear on the initial load, but it does when I refresh the page.

## Expected behavior

The tabs should load the same way after reloading and navigating to the page.

## Actual behavior

The tabs load differently if we refresh/reload the page vs. if we naturally navigate to the page.

The contents inside the Tabs are static
```tsx
    <Page
      fullWidth
      title="Some Title"
      separator
    >
      <Layout>
        <Layout.Section>
          <Card sectioned>
            <Tabs
              tabs={tabs}
              selected={tabIndex}
              onSelect={handleTabChange}
            >
              <Card.Section>{tabs[tabIndex].component}</Card.Section>
            </Tabs>
          </Card>
        </Layout.Section>
      </Layout>
    </Page>
```

## Steps to reproduce the problem

1. Set up server-side rendered React application
2. Reload page that contains Polaris tab components

## Reduced test case

I followed the example in https://polaris.shopify.com/components/navigation/tabs and wrapped it in a sectioned Card and a Polaris Layout component.

The issue exists with SSR.

## Specifications

```bash
  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.24 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.19.1 - ~/.dev/yarn/1.19.1/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.4
  npmPackages:
    @shopify/polaris: 4.10.2 => 4.10.2
    react: 16.12.0 => 16.12.0
    react-dom: 16.12.0 => 16.12.0

```

**Comment by AndrewMusgrave** [comment]
👋 Hey! Would you mind create an issue in your project repo with detailed steps on how to reproduce this issue so we can debug it? 😄

**Comment by AndrewMusgrave** [comment]
I don't seem to be able to replicate this using `nextjs`

**Comment by djoksimo** [comment]
Bug does not occur in production so i am going to close this issue. Thank you @AndrewMusgrave  for looking into this!!

**Comment by apman** [comment]
Just in case others run into this - we encountered this issue in tests after bumping Sewing-Kit from 2.0.2 to 2.1.3. The problem occurred intermittently wherever we were relying on DOM rendering for our tests. 

I have isolated the problem and it can be [demonstrated it on the Polaris tabs sample code](https://github.com/Shopify/data-portal/pull/4875) by testing for `expect(subject.find('Tab')).toHaveLength(n);`

**Comment by sixkin-stephens** [comment]
@djoksimo , this should be reopened, as it's an easily reproducible and highly visible bug.

I first encountered it using the Tabs component in a remix-based app extension that I'm developing. Now I'm encountering it with the IndexFilters component, which presumably utilizes the Tabs component internallly.

The Tabs do not render until the mouse is moved over the client area forcing a rerender. It's not like a few pixels are messed up. The Tabs are completely MIA until a rerender is forced. Every time that I refresh the page during development, I have to remember the extra work-around step of moving the cursor over the client area, to force the Tabs to appear. This is super annoying!

This is not a subtle issue. I wasted time trying to diagnose it, until I eventually found this [issue](https://github.com/Shopify/polaris/issues/2706). You can safely assume that many other Polaris developers will run into this during the development cycle.

Just because it "does not occur in production" is not a good reason to ignore it. Polaris-react is a really nice framework. But a highly visible and annoying bug like this detracts from it's development usabilty and makes a poor impression.
