### ISSUE TITLE
Color system documentation

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react#2719]
Create documentation for the design language rollout in GitHub

**Comment by BPScott** [comment]
Considering the majorifty of this code now lives in the polaris-tokens repo would it be better to document it in there?

**Comment by sarahill** [comment]
Yea I was wondering about that. I think the plan is to move it to Polaris tokens but I can see it being useful to go ahead and do that.

**Comment by danrosenthal** [comment]
I think it makes sense for this documentation to live in Polaris Tokens. We would also want to add a README for the Polaris React Theme Provider, and have any implementation-related documentation there. We would also want to expand the Polaris Rails Theme Provider docs to include implementation details for that library. Finally, we'd want heavy cross linking between these docs, so that folks could get the complete picture without the need for redundant content sources to maintain.

**Comment by sadiesaurus** [comment]
I've started populating some new docs for this in polaris-tokens: https://github.com/Shopify/polaris-tokens/pull/102
