### ISSUE TITLE
Is this state of the art Polaris?

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#2922]
I am rendering a resource list. Has some data. A company name in h2 tags, name, phone, email, and an URL, all rendered with just a p tag. My choice is a table, or a resource list. I need to transition these entries to some statuses like active or archived... so a button or some other control. 

To the punchline. To me, this whole look does not look good. Yet it is virginal Polaris. So it is what it is. Am I supposed to now overwrite the Polaris Sass to generate my own CSS to make this look good? Like why is an H2 indistinguishable from p. Is that me or Polaris. Why are resource list items not able to have fancier layout options, like cells. Am I supposed to invent that too? I wish these components were sexier I guess? I expected more for Resource Items I guess. 

Excuse my lack of experience with Polaris, I started with v1 and gave up, then v2 and gave up, and only now am I revisiting it, and I am somewhat confused. It works, but I am getting glamour. 

This is what I am talking about... 

[screenshot](https://www.evernote.com/l/ACcW8AkVQtpBBb4w0O_zzLgLeCe0E8c4ScEB/image.png)

**Comment by BPScott** [comment]
> Like why is an H2 indistinguishable from p

On any given page your heading hierarchy (and thus if you use a `h2` or `h3`) may be independent from how much visual weight you want to give to any one of those headings, because of that we separate out semantic meaning from visual styling. 

Consider a world where h1, h2, h3, h4 and p all have different sizes, and in this world you have a page marked up with a bunch of h2s with h3 as subheadings underneath them, all sized in the way you want. Now you decide you need to add an additional section to that page - you add a heading at the top of all your existing content and now all your h2s have to become h3s, and h3s have to become h4s to maintain the right heading hierarchy for the sake of accessibility. Now all the headings have a different size, which you probably didn't want!

You'll need to use the [Heading](https://polaris.shopify.com/components/titles-and-text/heading) and [Subheading](https://polaris.shopify.com/components/titles-and-text/subheading) (and other elements in the "titles and text" section to render your headings.


> Why are resource list items not able to have fancier layout options, like cells. Am I supposed to invent that too? I wish these components were sexier I guess? I expected more for Resource Items I guess.

We aim to codify the most common patterns and give people the freedom to perform more complex patterns themselves, we don't aim to be a panacea for all potential needs. This means providing lower level building blocks that you still have to combine to get the design you desire :)

You can customize the children of `ResourceItem` however you wish. If you want to create multi column layouts you might want to use [`Stack`](https://polaris.shopify.com/components/structure/stack) as our abstraction over flexbox. We don't currently offer an abstraction over CSS grid as we've found that most of the time it's easier to just write some of your own CSS because grid is that dang powerful. Alternatively if you need columns, perhaps it is a [`DataTable`](https://polaris.shopify.com/components/lists-and-tables/data-table) you're after?

**Comment by resistorsoftware** [comment]
Ok. Cool... thanks

**Comment by raghu-c** [comment]
Well detailed @BPScott

**Comment by resistorsoftware** [comment]
It is unfortunate that the project is without practical implementation details in the documentation to date. It is understandable from the perspective that it keeps changing, but there seems to be a serious dearth of external contributions. When one searches the Internet for Polaris and practical use information, almost 100% of the hits are Shopify domain. No one blogs about their use and findings. No one has Github repos demonstrating cool effects. It is like a ghost town out there, strange considering it has been around for a few years now. 

Anyway, yes, that explanation helped me, as in a matter of minutes, I changed my code and suddenly my App "looks" a lot better!!
