### ISSUE TITLE
Polaris, App Bridge React and Navigation!! Help

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#2966]
DESIRE:  in my Resource Item, something like this link... 

    <Link url="/admin/collection/123456789"> My Collection</Link>

Without 4000 lines of code or Typescript. Is it possible to make link in my embedded App code that jumps to the Admin? In Javascript. 

Is that even possible? I can do this with Non-Polaris Apps, but not with Polaris React. 

All the documentation I have seen and read on Navigation and Routes are not helpful, they are very vague and less than HelloWorld useful. One request in here recently pointed out how hard it is to do, but I could not follow their typescript code. Could someone on the Polaris team please Codepen a simple LINK... to the Admin for me. 

Seems like a reasonable thing to ask for?

**Comment by BPScott** [comment]
Can you show me what you've set as your `<AppProvider>`'s `linkComponent` prop?

**Comment by resistorsoftware** [comment]
I am not sure... what you want... 

     <AppProvider>
      <Provider config={config}>
        <TitleBar title="Dashboard" />
          and eventually, I render a <ResourceList> with <ResourceItems>

And in my resource item... I want a clickable link to the collection ID... so simple in HTML... and 4000 lines of React... maybe... hehe

    <ResourceItem
      id = {id}
      company = {company}
      first_name = {first_name}
      last_name = {last_name}
      email = {email}
      phone = {phone}
      shopify_domain = {shopify_domain}
      collection_id={collection_id}
     >
    <Link url="https://mystore.myshopify.com/admin/collections/collection_id">The Collection</Link>

**Comment by resistorsoftware** [comment]
I don't understand why 20 years of HTML gave us the perfect <a> element, and I cannot use one in my App because, well, it is so complex, you need a PhD in Astrophysics to make a clickable link go somewhere... 

My App is great and all, but when I chose the Polaris React toolkit to try something new I was not counting on it being so hard to do simple things.

**Comment by BPScott** [comment]
`<Link url="https://mystore.myshopify.com/admin/collections/collection_id">The Collection</Link>` seems pretty reasonable. What's happens currently when you click it? You seem to claim "it doesn't work" and several laments of general web development, but you never describe HOW it doesn't work and without that I can't really guide you towards what you're missing.



> I don't understand why 20 years of HTML gave us the perfect element, and I cannot use one in my App because, well, it is so complex, you need a PhD in Astrophysics to make a clickable link go somewhere...

You absolutely could just do `<a href="/admin/collection/123456789">Hi</a> in your App. There's nothing stopping you from writing that. What happens if you write that and click the link?



I'm guessing this is going to boil down to the embedded app is within an iframe so you need to add a `target="_top"` to your `a` tag.

**Comment by resistorsoftware** [comment]
Sorry... my explanation was poor. If I place a <Link> with text... it would work. url="https://google.com" would indeed work. Hence Link does its job. But when iterating a list and rendering ResourceItems, I am having trouble generating the url dynamically. Nothing I do makes a nice link with the right data!

My weakness is not knowing the "new Skool" stuff of needing a library of code "React Router" to make a link system work. I get it. There is no shortcut. I have to agree to use the things that arose to replace the things that were... 

OK.. my point remains... there are no good examples of a simple link in an embedded App, where a merchant could click and be viewing a product, collection, customer or other admin resource, without pain... 

None of that is Polaris fault. It is just the chaos of front-end JS...

**Comment by BPScott** [comment]
> Sorry... my explanation was poor. If I place a Link element down with text... it would work as in url="https://google.com". Hence Link does its job. But when iterating a list and rendering ResourceItems, I am having trouble generating the url dynamically. Nothing I do makes a nice link with the right data!

https://polaris.shopify.com/components/lists-and-tables/resource-item offers up an example of how to render a ResourceItem inside an array that shows an example of passing a url around.


If it is variable interpolation you're struggling with then you can use backticks to enter a dynamic value into a prop. The following would return a Link with the url of `https://example.com/id/6`

```
function MyComponent() {
  const someId = '6';

  return <Link url={`https://example.com/id/${someId}`}>Click me</Link>
}
```

---

Regarding react-router:  I realized we had a blind spot with docs for integrating with that last week. Earlier I made https://github.com/Shopify/polaris-react/pull/2967 to document how part of that integration works - which is why I was asking about your `AppProvider`'s `linkComponent` earleri.

**Comment by resistorsoftware** [comment]
I struggle with the concepts as there are so many options from the last 3-4 years of React development, of which I chose to not participate in. So I see Class based components, and functional Components, and then the introduction of Hooks, and then the Shopify sample code which shows off concepts, but also mixes in these various styles, and without much in terms of examples. 

A simple example is the use of the Context component from App Bridge React. I am aware that I can use that to get access to the underlying App, which is required for Redirects and stuff, but for the life of me, looking through the docs, I cannot fathom how to actually use that. 

Not a complaint about Shopify or Polaris or React, but this tooling is very hard to pick up for those of us that do not use React on a daily basis. I expected a learning curve, sure, but the dearth of examples out there is what is really slowing my uptake. 

Anyway, thanks for the tips... I do appreciate it.
