### ISSUE TITLE
ResourceList renderItem

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#3004]
The docs say a **renderItem** function has three **required** parameters, an item, an id and an index. OK. All the examples just send an item, so I am not understanding why the id and index don't throw some kind of error. 

My point is, I would like to know when the last item in the list of items is rendered. The parent component, the **ResourceList** knows how many items it has, but apparently, there is no easy way to render the items where one could mark up the last one different from say the first one. 

What is a good hack for this that is not going to mangle the Resource List? Specifically, I want to know the cursor associated with the last item of the list and I want to trigger a fetch when the last item in the resource list becomes visible.

**Comment by chloerice** [comment]
Hi @resistorsoftware 👋 The callback that you set on `ResourceList.renderItem` can expect to be called with those parameters, but you're not _required_ do anything with them. In the case of our examples, the item parameter is all we care about. But it sounds like the index will be useful for you to know so that you can compare it to `{The array you set on ResourceList.items}.length` and conditionally render whatever it is you want to be different in the last item.

**Comment by resistorsoftware** [comment]
Hi,

OK. So I console logged and sure enough, I get the item, id and index. Inside the renderItem function, how do I get the value of the length of the number of items being rendered? I don't understand how I can compare the index to the total number of items being rendered. Help?

**Comment by resistorsoftware** [comment]
OMG: I am so dumb... OK... got it... 

  {index === data.products.length - 1 ? (<p>LAST OF US!</p>) : null}

And I can now try and see about fetching more data when the last item in the resource list becomes visible to the end user.
