### ISSUE TITLE
[Color Picker] colorToHsla not exported

### ISSUE THREAD

**Issue by gurkanoluc** [Shopify/polaris-react#3033]
Hi folks, when I was trying to use color picker and wanted to convert between Hex and HSBAColor realised that `colorToHsla` is not exported at https://github.com/Shopify/polaris-react/blob/master/src/index.ts#L17 here, although it's exported in https://github.com/Shopify/polaris-react/blob/master/src/utilities/color-transformers.ts#L299. Is there any specific reason for that?

## Expected behavior

`colorToHsla` utility function should be exported as well, given it's quite handy.

## Actual behavior

Although other helper methods such as `rgbToHex` are exported, `colorToHsla` is not exported.

**Comment by BPScott** [comment]
Per my response to #3090, which also dealt with color functions:

My current opinion is that these color utilities shouldn't be public exports, they should be internal utilities only. I don't believe we document or recommend their usage anywhere. When we add something to our public API surface area we make a promise to keep supporting it and it makes refactoring any internals that depend upon those utility functions much harder. Because of that I want to keep out public API surface area as small as possible - ideally only components and types for their props. There are a few exceptions to this but they're mostly down to accidents rather down to explicit decisions that something needs to be public.

I believe the only reason why these color utility functions are public currently is that they were publicly exported accidentally at some point and then when I moved some imports around it turned out that somebody was already depending on them so they had to stick around. I've not yet had the time and strength to work our how to remove these in a major version. I think the effort would be pretty low but my focus has been elsewhere.

So I'm going to close this for reasons stated above - these color utility functions shouldn't be public and the only reason they are currently is due to oversight and then not wanting to break backwards compatibility.

**Comment by gurkanoluc** [comment]
Thanks for the detailed explanation @BPScott.

**Comment by Shine18** [comment]
@BPScott These should be public and included in the docs as helper/utilities functions, because they really help, when creating an interface for merchant to customize something on frontend and generating the colors in rgb/hex to use in css.

**Comment by emcmanus** [comment]
You can always
```js
import { rgbString, hexToRgb, rgbToHex, rgbToObject } from '@shopify/polaris/dist/esm/utilities/color-transformers'
```

Your packager will let you know if these go missing.
