### ISSUE TITLE
External contributions always fail CI

### ISSUE THREAD

**Issue by amrocha** [Shopify/polaris-react#3041]
## Issue summary

See https://github.com/Shopify/polaris-react/pull/2843

The problem is that we have two Travis builds: one for branches, and one for PRs. The PR one doesn't run Percy/shrink-ray/chroma because of the way Travis handles merging the PR changes causing issues according to a comment by Ben:
```
 # Travis builds on commit and for PR builds (where Travis merges your last
 # commit in a PR into the base branch). There isn't much value uploading info
 # to ShrinkRay/Percy/Chroma for these merge commits because they're not
 # usefully exposed in their UIs. So skip these jobs on PR builds
```

The problem with this is that branch builds don't run for outside contributions, so they always get stuck on CI.

## Expected behavior

CI runs for external contributions

## Actual behavior

CI gets stuck waiting for responses from services that were never triggered by Travis

**Comment by amrocha** [comment]
@BPScott If you have any ideas how to handle this it'd be useful for the discoverability job too

**Comment by BPScott** [comment]
This is somewhat annoying: 

- running these scripts twice is kinda wasteful
- running them only on pushes means that external contributors don't get value
- running them on PRs only means that if i push an arbitrary branch up then i don't get the value without opening a PR.
- running them on PRs might break the resultant ui as the commit that travis creates doesn't map to something actually on the branch (as it is merged with master)

Part of me wonders if this can be sidestepped by moving using GH Actions for builds instead of Travis.

**Comment by BPScott** [comment]
We could update our required checks to make the checks that don't run on forks not be required, so that they don't block PR merge

**Comment by BPScott** [comment]
Eeey we actually fixed this with the move to GH actions!
