### ISSUE TITLE
[New DL] Modal opened by contextual save bar is using inverted palette

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#3219]
## Issue summary

A user opens a confirmation modal from the contextual save bar the colors of the modal are inverted.

## Expected behavior

When a user gets a confirmation modal from the contextual save bar the color should be not inverted.

## Actual behavior

![image (1)](https://user-images.githubusercontent.com/19199063/92278654-ae635400-eec3-11ea-9117-f710233cc193.png)

**Comment by husshegz** [comment]
With the new button changes, the `secondaryAction` (or `discardAction` button) looks inconsistent with its borders on top/bottom. This seems noticeable right now, only because the `ContextualBar` as well as the `Modal` that opens after it is dark (in dark mode?). Potentially, this will be fixed once both components are a lighter color and will not demand extra attention. 

Here some screenshots for reference:

## Context bar cancel button
![image](https://user-images.githubusercontent.com/23648577/93510346-0439f200-f8ef-11ea-883d-f5bd4a34b4a2.png)

## Clicking on Cancel opens dark modal with same inconsistent secondary action
![image](https://user-images.githubusercontent.com/23648577/93510473-3cd9cb80-f8ef-11ea-89da-ead9e0cce34c.png)

**Comment by dfmcphee** [comment]
I noticed this too on the most recent changes. I believe the modal is getting the dark mode theme because it is nested within the context bars theme provider [here](https://github.com/Shopify/polaris-react/blob/master/src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx#L129). I'm going to put up a PR to move that out but that doesn't solve the button issues.
