### ISSUE TITLE
[new DL] Resource List header should not have sharp top corners

### ISSUE THREAD

**Issue by Ipkhchan** [Shopify/polaris-react#3248]
## Issue summary

<img width="455" alt="Screen Shot 2020-09-09 at 3 47 52 PM" src="https://user-images.githubusercontent.com/29233959/93132152-064f4700-f68a-11ea-86d4-8a0252d921c5.png">

## Expected behavior

- Resource List header should have rounded top corners

## Actual behavior

- Resource List header has sharp top corners

## Steps to reproduce the problem

- view Resource List with header in the polaris storybook with the new design language enabled.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by AndrewMusgrave** [comment]
👋  Resource list edges should be rounded. The problem is likely with card without a card section. 
```tsx
<Card>
  <ResourceLiset>
```

Adding a section should fix the rounded edges

```tsx
<Card>
  <Card.Section>
    <ResourceLiset>
```
Unfortunately, that'll add additional padding. You can use the `fullWidth` prop to removed the horizontal padding but still have the vertical padding. If that's a problem Polaris is always open to contributions 😄
