### ISSUE TITLE
Support for server side render

### ISSUE THREAD

**Issue by SecretBase** [Shopify/polaris-react#326]
Sorry for raise a question in issues tracker.

May I know are Polaris's react components all supporting server side render. I can't find any related documentation for server side render for polaris. It quite hard for us to testing components or reading the components source code one by one to check the support.

We want to building fast first print time for shopify users and SSR is essential.

**Comment by ry5n** [comment]
Hi @SecretBase! Our intention is for all components to support server-side rendering.
Currently I know that the new DataTable doesn’t, but we’re working on a fix. I don’t expect there are many others like that—we use almost all the existing components in our own codebase, which uses server rendering.

If you ever do run into SSR issues with Polaris, please open a specific issue and we’ll get it fixed.

**Comment by SecretBase** [comment]
@ry5n  Thank you for the update. Keep up the good work.

**Comment by montalvomiguelo** [comment]
Any news in v3?

**Comment by tmlayton** [comment]
The only known and outstanding issue related to server side rendered was due to app bridge in the `AppProvider`. This was fixed in #696 and has been released as of `v3.2.0`, although I recommend using `v3.2.1` as there were a couple TypeScript related errors fixed.

I did an audit of all other components by manually testing server side rendering for each component which referenced window or document to make sure this happened after 1st render (e.g. `componentDidMount`). I think we’re good now so I’m going to close this issue. If you come across another component which does not support server side rendering, please open a new issue for the specific component.
