### ISSUE TITLE
New Design Language

### ISSUE THREAD

**Issue by Popesites** [Shopify/polaris-react#3569]
## Feature request summary

Introducing the new design language into Polaris.

## Rationale

With the updated design language being used throughout the Shopify admin, embedded apps look very out of place. 

I am wondering what the timeline is for bringing in these design language changes into Polaris, so that embedded apps can continue to enjoy a sameness with the rest of Shopify.

---

**Comment by asacarter** [comment]
Can't believe a major UI refresh was released direct to the main shop admin without being available to developers via a Polaris update first.

**Comment by BPScott** [comment]
Hi folks. Large portions of this redesign started in this repo. You can enable this by setting setting the feature on your AppProvider `<AppProvider features={{newDesignLanguage: true}}>`.

This is documented on https://polaris.shopify.com/components/structure/theme-provider though it looks like that needs to some updates to its "production readyness" information.

**Comment by Popesites** [comment]
Hi @BPScott which version was this added?

**Comment by BPScott** [comment]
The feature toggle was added ages ago and since then we've been continually refining our new design language, so saying "X is the minimum supported version" doesn't really make sense as "the new Design Language from 4 months ago" isn't the same as "the new Design Language used in the latest version of `@shopify/polaris` and thus in the Admin". If you want to keep in sync with what the Admin looks like you should update to the latest version - at time of writing v5.10.0.
