### ISSUE TITLE
Consolidate 4xx/5xx error page styles

### ISSUE THREAD

**Issue by AdamWhitcroft** [Shopify/polaris-react#3597]
We're currently using two icons for 4xx/5xx errors respectively. I'm proposing we unify these screens, use a single icon throughout and potentially make the content on these pages more targeted to the error if we feel like that's something that's important to merchants (my gut is that it's not helpful / useful for most of them to know the error code).

<img width="624" alt="Screen Shot 2020-11-03 at 9 25 48 AM" src="https://user-images.githubusercontent.com/861526/97997105-9cfcd200-1db6-11eb-88c2-a2369e010ff0.png">

<img width="1635" alt="Screen Shot 2020-11-03 at 9 25 43 AM" src="https://user-images.githubusercontent.com/861526/97997109-9ec69580-1db6-11eb-89f7-1556b1d1bc6e.png">

Context conversation:

<img width="1444" alt="Screen Shot 2020-11-03 at 9 26 35 AM" src="https://user-images.githubusercontent.com/861526/97997177-b140cf00-1db6-11eb-92f4-f306982e0014.png">

Edit: Apologies for the insta-close, my mouse derped out.

**Comment by alekmackie** [comment]
Thanks Adam! IIRC @claydelk took a look at the content for these states last year and determined that it would be best not to surface the error codes.

**Comment by claydelk** [comment]
I think we did because like Adam said, they're not very helpful to people. But if we could actually give people a way to troubleshoot by giving them a specific code, that would totally be worth it. 

I took a quick look and it doesn't look like we have a Help resource for common error codes. But if we did, I'd be up for including those.

**Comment by AdamWhitcroft** [comment]
🙏
