### ISSUE TITLE
Modal and Application Communication

### ISSUE THREAD

**Issue by khiconit** [Shopify/polaris-react#383]
How i can access to iframe in modal ?
i  can't find it in document
as seem your document very poor.

**Comment by superwhykz** [comment]
@khiconit https://polaris.shopify.com/components/embedded/embedded-modal

**Comment by khiconit** [comment]
I mean how i can access to modal content like that
[https://help.shopify.com/en/api/embedded-apps/embedded-app-sdk/features#modal-and-application-communication](url)

**Comment by ry5n** [comment]
Can you explain more what you’re trying to achieve, in terms of your app’s functionality or the user experience?

**Comment by khiconit** [comment]
Hi,
 i want i can access to Content in iframe (React js) like [https://help.shopify.com/en/api/embedded-apps/embedded-app-sdk/features#modal-and-application-communication](https://help.shopify.com/en/api/embedded-apps/embedded-app-sdk/features#modal-and-application-communication)

**Comment by ry5n** [comment]
When you’re using Polaris react, you need to provide the `Modal` component’s `src` prop with a URL from your own application. Since the URL is a page you control, the Polaris API doesn’t have the same concept of reaching into the modal in the same way as the EASDK.

If you can describe what you’re trying to achieve in more detail, I can probably provide more specific help.

**Comment by khiconit** [comment]
You mean i can't access to iframe when it opened ?
_ShopifyApp.Modal.window().$("body")_

**Comment by ry5n** [comment]
I looked into this some more, and I understand that this is painful right now. Especially with React, it’s not ideal to be reaching into the DOM. For this and other reasons we’ve decided not to expose the iframe content in Polaris the way the EASDK does. This has made things more difficult in the short term, even for our own developers (we use the EASDK in our own apps too). We’re exploring ways to make this better right now.

For the time being, I can outline some of the solutions you can try, most of which we’ve used ourselves. In these points I’ll talk about the modal iframe (which holds the page you point to with the Modal’s `src` prop) and the embedded iframe (which holds the current page in your embedded app).

- [Localstorage](https://developer.mozilla.org/en/docs/Web/API/Window/localStorage). If you need to communicate between the modal iframe and your embedded app, such as when the modal contains a form, you can use localstorage to store the form values. In your embedded iframe, you can retrieve the values from localstorage when the modal is closed.
- [React portals](https://reactjs.org/docs/portals.html). You can create a single page in your app that acts as the `src` for all modals. When this page is loaded, you can postmessage to the embedded iframe to signal the modal iframe’s DOM is loaded. Then, you can use a portal to “transport” some content from your embedded iframe into the modal. This way the embedded iframe and the modal content can share state.
- Using the normal EASDK along with Polaris. You can choose not to pass your `apiKey` and `shopOrigin` to the `AppProvider`, and instead use the EASDK itself in combination with Polaris React.

None of these suggestions is ideal, I know. Please bear with us as we work to make this better, and let me know if you have any more questions or comments.

**Comment by khiconit** [comment]
Oh, sad  ;(
I think that  postmessage  via iftame is the best of way in this case
Thanks for your ideal

**Comment by ptcampbell** [comment]
Thanks for the workaround ideas @ry5n.

I can understand why you mightn't want to reach into DOM from a technical perspective. I came to the conclusion it wasn't really worth the effort in working around the limitations, so I ended up abandoning the EASDK altogether. 

Which is fine, I guess it did improve the developer experience a bit. I just wonder whether it runs counter to the goals of a cohesive design system in the first place if in all likelihood the app I am working on will no longer sit within Shopify.

**Comment by ry5n** [comment]
The technical issues aside, I believe stand-alone apps _can_ still benefit from using the same design language so that merchants feel at home. At the same time, non-embedded apps should take care to differentiate themselves (using color, a logo, or the way the application frame is structured) so that merchants are aware they’re a different product.

[Shogun](https://apps.shopify.com/shogun) does a good job of this IMO ([screenshot](https://s3.amazonaws.com/shopify-app-store/0ca2c1526ec07b9f52021bd42651b1fd/screenshot/43568/original.png)).

That’s not to minimize the challenges we’ve discusses in this issue. If you liked the idea of creating an embedded experience, we hate to see you not able to achieve it, and as I said before we’re working on ways to make this much less painful.

**Comment by ptcampbell** [comment]
Hi Ryan. I totally agree with you, and Shogun is a great example. 

I am not abandoning the design language, just the idea that it should be embedded. Not embedding the app provides me with an opportunity to add a bit more brand personality and will make for a possibly nicer experience. Whether that's ideal from Shopify's perspective is a different question though. 

No complaints from me in any case, and thanks for sharing the alternative approaches.

**Comment by ry5n** [comment]
Oh, totally. [We support both embedded and non-embedded apps](https://polaris.shopify.com/guides/designing-apps#decide-when-polaris-is-right-for-your-app), and there are good reasons to go either route, depending on your needs. Branding is one good reason for choosing a stand-alone app.

**Comment by tmlayton** [comment]
@ptcampbell I’m very interested to hear what you discover.

**Comment by ncpope** [comment]
Maybe there could be an option to display it within the iframe of the embedded app if the developer doesn't want to use the src attribute on the embedded modal. This way we could use children in the component and not have to worry about a complex work-around.

In my experience stuff that breaks the standard way of doing things can be a real pain to maintain further down the road when you've forgotten how the complex thing that you did as a work-around functions. The way that it works now seems really opinionated and not at all intuitive.

I've seen several related issue reports when trying to research this and it seems a lot of people are running into the same issue repeatedly.

I like that there is a way to completely take over the screen like a native part of Shopify but I just wish there was an option for apps that don't really need that capability.

Personally, I'm going to create a less intuitive UX just to make this easier to maintain.

**Comment by sam-cnet** [comment]
> Oh, sad ;(
> I think that postmessage via iftame is the best of way in this case
> Thanks for your ideal

What you are trying to do is communicate between child and parent component. This is more of a ReactJS question because you want to for example display a form in the modal right? If so then you need to pass a function as a prop. You can use the primaryAction prop that's built into the Modal component, it's meant for this very reason, at least the only real option for an embedded app.  

https://github.com/Shopify/polaris-react/issues/876

**Comment by tmlayton** [comment]
Thanks everyone for your participation in this issue. Closing for now as the original question has been answered. As of v5.0.0 we will be removing App Bridge from Polaris and moving those components to their own `@shopify/app-bridge-react` library.

More information will come with docs, etc, but for those immediately curious read https://github.com/Shopify/polaris-react/issues/814#issuecomment-493249756

**Comment by ptcampbell** [comment]
Hello again 👋

Sorry to raise this one from the dead, but I have a couple of questions and I didn't really fancy opening a new issue.

I see that the Modal component is being deprecated. I can understand why you would want to do this, but I'm not seeing `@shopify/app-bridge-react` anywhere and I'm wondering what is actually going to change? Does the app bridge house actual components? Will they be any different to the existing ones? Since they cater specifically for embedded app experiences, will there be appetite on Shopify's end for providing a richer experience? (e.g. forms)

I guess I am hoping for an official way of doing this, but am also wondering if I should give up on this and design around the problem. Which would be a shame because it's a pretty common pattern within your own admin UI let alone elsewhere. 

There are workarounds, but I am worried that they may stop working if the API changes. That is why I think it's important to consider supporting it "officially".

Here is an example of what I mean by a rich experience. 

![image](https://user-images.githubusercontent.com/876594/59655934-d9dc1080-9150-11e9-933b-0abbe0b33ce5.png)

**Comment by avibz1987** [comment]
Is this still the official solution? 3 years later?
