### ISSUE TITLE
[Page] Add custom accessibility label to rolled up actions button

### ISSUE THREAD

**Issue by lsit** [Shopify/polaris-react#4072]
## Feature request summary

- Allow a custom accessibility label to be passed to the `RollupActions` activator button to enhance the generic "Actions" text

## Rationale

<img width="390" alt="Screen Shot 2021-03-22 at 3 38 11 PM" src="https://user-images.githubusercontent.com/12960456/112048275-9d5af700-8b24-11eb-9e1d-1d9e62ea9024.png">

When the screen size is smaller, the secondary actions and grouped actions roll up into an actions menu (i.e. the "..." button). This "..." button is read by screen readers as "Actions" ([example](https://videobin.shopify.io/v/Wo5pr)). It would be great if we could customize the accessibility label to be more specific.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by emma-boardman** [comment]
Hey 👋 

I wonder if it would be possible to enforce a pattern here, for future consumers who might be less aware of accessible labelling. For example, if the default text is `Actions`, the override could be `Actions {custom text}`. 

The consistency would benefit users navigating via voice-command or the rotor menu. 

My imagined use-case is:

- User utilising voice-commands is accustomed to secondary-action buttons being labelled `Actions`
    - The voice-command `Actions button` would flag `Actions {custom text}`, but wouldn't flag `More Actions Navigation` 
    - ref: https://www.sarasoueidan.com/blog/accessible-text-labels/

It might also be beneficial to add the custom text after the default label rather than before. 

Imagined use-case:

- User navigating via the Rotor menu is accustomed to secondary-action buttons being labelled "Actions"
   - Custom content at the end of the label ensures the `Actions` buttons are still grouped in the rotor menu, which would be inline with the user's expectations

**Comment by lsit** [comment]
Thanks for the context @emma-boardman! That makes a lot of sense. TIL 😄

**Comment by gretchen-willenberg** [comment]
I agree that Diana's recommendation of `View Actions` works generically and also agree with Emma that additional context could be added when available. Here, the overflow menu includes additional navigation actions so, `View navigation actions`

![IMG_3875](https://user-images.githubusercontent.com/68568732/119834217-c0f84000-becd-11eb-89ca-1f2cd1e6c354.PNG)
