### ISSUE TITLE
[IndexTable] How can I click LINK to redirect to the page instead of selecting?

### ISSUE THREAD

**Issue by zhiyicai** [Shopify/polaris-react#4138]
I am using Shopify Polaris IndexTable https://polaris.shopify.com/components/lists-and-tables/index-table

How can I click LINK to redirect to the page instead of selecting?

https://user-images.githubusercontent.com/13891311/115785388-a8bd6e80-a3bf-11eb-87d7-ca7eccb73c3a.mov

**Comment by itsniper** [comment]
I hit the same issue over the weekend and this seems to be either a bug or unimplemented. There is a way to get it working though. I dug through the source code and `Row` tests and figured out that you need to have an `a` tag with the `data-primary-link` data attribute.

For example, see this line in `Row` tests: https://github.com/Shopify/polaris-react/blob/0ab82330d35444c6d7f19c303b200c22c9340cbd/src/components/IndexTable/components/Row/tests/Row.test.tsx#L76

This is the line in the source: https://github.com/Shopify/polaris-react/blob/0ab82330d35444c6d7f19c303b200c22c9340cbd/src/components/IndexTable/components/Row/Row.tsx#L80

However, searching the rest of the Polaris source I couldn't find anywhere that data attribute is set. So my current working solution was to add the `a` tag myself instead of relying on the `Link` component.

```javascript
<IndexTable.Row
          id={id}
          key={id}
          selected={selectedResources.includes(id)}
          position={index}
        >
          <IndexTable.Cell>
            <a className={"Polaris-Link Polaris-Link--monochrome Polaris-Link--removeUnderline"} href={url} data-primary-link={true} data-polaris-unstyled={true}>
              <TextStyle variation={"strong"}>{name}</TextStyle>
            </a>
          </IndexTable.Cell>
          <IndexTable.Cell>{location}</IndexTable.Cell>
          <IndexTable.Cell>{orders}</IndexTable.Cell>
          <IndexTable.Cell>{amountSpent}</IndexTable.Cell>
        </IndexTable.Row>
```

**Comment by zhiyicai** [comment]
> I hit the same issue over the weekend and this seems to be either a bug or unimplemented. There is a way to get it working though. I dug through the source code and `Row` tests and figured out that you need to have an `a` tag with the `data-primary-link` data attribute.
> 
> For example, see this line in `Row` tests:
> 
> https://github.com/Shopify/polaris-react/blob/0ab82330d35444c6d7f19c303b200c22c9340cbd/src/components/IndexTable/components/Row/tests/Row.test.tsx#L76
> 
> This is the line in the source:
> 
> https://github.com/Shopify/polaris-react/blob/0ab82330d35444c6d7f19c303b200c22c9340cbd/src/components/IndexTable/components/Row/Row.tsx#L80
> 
> However, searching the rest of the Polaris source I couldn't find anywhere that data attribute is set. So my current working solution was to add the `a` tag myself instead of relying on the `Link` component.
> 
> ```js
> <IndexTable.Row
>           id={id}
>           key={id}
>           selected={selectedResources.includes(id)}
>           position={index}
>         >
>           <IndexTable.Cell>
>             <a className={"Polaris-Link Polaris-Link--monochrome Polaris-Link--removeUnderline"} href={url} data-primary-link={true} data-polaris-unstyled={true}>
>               <TextStyle variation={"strong"}>{name}</TextStyle>
>             </a>
>           </IndexTable.Cell>
>           <IndexTable.Cell>{location}</IndexTable.Cell>
>           <IndexTable.Cell>{orders}</IndexTable.Cell>
>           <IndexTable.Cell>{amountSpent}</IndexTable.Cell>
>         </IndexTable.Row>
> ```

thank you

**Comment by zhiyicai** [comment]
> Instead of an `a` tag you can also just wrap it in a `div` e.g.
> 
> ```js
> <div data-primary-link>
>   <TextStyle variation="strong">ABC</TextStyle>
> </div>
> ```
> 
> and then use the onNavigation prop on `IndexTable.Row` e.g.
> 
> ```js
> const handleOnNavigation = useCallback((id) => {
>   // route with id
> }, []);
> ```
> 
> ```js
> <IndexTable.Row
>   id={id}
>   key={id}
>   selected={selectedResources.includes(id)}
>   position={index}
>   onNavigation={handleOnNavigation}
> >
>   <IndexTable.Cell>
>     <div data-primary-link>
>       <TextStyle variation="strong">ABC</TextStyle>
>     </div>
>   </IndexTable.Cell>
> </IndexTable.Row>
> ```

Thank you very much

**Comment by carlfranciscastillo** [comment]
To add to this you can actually use the `Link` component as long as you prevent the event from propagating

**Comment by TheSecurityDev** [comment]
> I came across this issue also today. Theres currently nothing in the documentation to explain how to navigate to a detail page from clicking on a row item.
> 
> Adding a `a` tag with a `data-primary-link` attr worked but took a while to work out.

This doesn't seem to work well on mobile. When I click the row, it opens the details page, but then after going back, it's still selected or something, and you can't select that row/link again. You have to click a different one. It seems to also happen periodically on desktop, but I can't reproduce it.

Edit: This seems to be related to #4345, but I think it might be a different issue, because the fix provided doesn't work.

**Comment by evan-north** [comment]
Maybe you can try:

import {useNavigate} from 'react-router-dom';

const navigate = useNavigate();
const handleOnNavigation = () =>{
    navigate("/detail");
  }

// detail is filename in pages folder

**Comment by RiccardoRoscilli** [comment]
Hello,
I'm trying to link an external pdf to print in the index table, but the data-primary-link works only inside the component where I create the index table. 
If I import a new component to inject the link inside the table cell, it follows the standard behaviour (row selection)
Anyone had the same issue?
