### ISSUE TITLE
Ship React 17

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react#4271]
This will eventually block web. We should align our release with the update of quilt to React 17. Project [here](https://vault.shopify.io/projects/19958)

**Comment by BPScott** [comment]
[The React 17 release blog post](https://reactjs.org/blog/2020/10/20/react-v17.html0 suggests changes are minimal. The changes to event delegation might be an issue but I don't think so.

Tangentally related to polaris v7 it would be great to bump the minimum react version to 16.14.0, so that you can leverage the new jsx transforms in the future.

Ideally you'd have a peerDependency that supports both 16.x and 17.x - '`^16.14.0 || ^17.0.0`

**Comment by BPScott** [comment]
Migration and testing be made easier by finishing off migrating from enzyme to `@shopify/react-testing` first.

**Comment by TheMallen** [comment]
An [exploration](https://github.com/Shopify/web-foundations/issues/227) into upgrading React in Shrink-Ray found Polaris seems to work fine with React 17.

We will be upgrading [react-testing to support 17.x ](https://github.com/Shopify/quilt/issues/1955) asap.

I think it should be relatively trivial to update here (though the changelog mentions event listener changes and Polaris is probably the most likely library to feel those in some edge case)
