### ISSUE TITLE
Audit vault content to make sure Polaris is used correctly

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#4481]

**Comment by jjgali** [comment]
Audited the Vault for any mentions of the alpha Polaris site, "system of systems," and "foundations." I was able to find 3 pages:
- [Designing on Checkout - Toolkit](https://vault.shopify.io/pages/11910-Designing-on-Checkout-Toolkit)
- [Process](https://vault.shopify.io/pages/8776-Process)
- [Content + Shopify’s Design System](https://vault.shopify.io/pages/6124-Content-+-Shopify%E2%80%99s-Design-System)

**Comment by jjgali** [comment]
Edited the first two pages, one last page remaining [Content + Shopify's Design System](https://vault.shopify.io/pages/6124-Content-+-Shopify%E2%80%99s-Design-System). This page has a lot to unpack and may take just a bit more time. Reach out to Brooke Jibb with recommendations on placement of content (possibility that this should live in our Vault section).

**Comment by jjgali** [comment]
[Content + Shopify's Design System](https://vault.shopify.io/pages/6124-Content-+-Shopify%E2%80%99s-Design-System) page has been updated. Waiting for approval from folks on the UX onboarding team, then I will communicate the changes to Brooke Jibb, who manages the UX Handbook.

**Comment by jjgali** [comment]
Changes pushed, and Brooke has been notified. For now, she's just going to communicate that the URL for the alpha site has been updated, since that's the most noteworthy change for readers. 

Edit: Also noticed a [slide deck](https://docs.google.com/presentation/d/1IYtIUjbLoWfu5srZY6K2Tmuv3NSLz6tSHEupajbLIcU/edit#slide=id.gf5e51afb26_0_0) floating around with the same content as this page. I added a banner to the deck, stating that it's no longer being maintained, and that the Vault page should be our source of truth.

**Comment by jjgali** [comment]
I know this ticket is closed, but I found one other page that I missed in the audit: https://vault.shopify.io/pages/8753-Tools

I've updated all the URLs pointing to the alpha site and replaced mentions of `Alpha Polaris` with `alpha Experiences`.
