### ISSUE TITLE
TypeScript can't resolve non-relative paths in type imports

### ISSUE THREAD

**Issue by kj** [Shopify/polaris-react#4507]
## Issue summary

I'm getting a couple of errors when running the TypeScript compiler with Polaris 7.0.0:

```
[9:12:31 pm] File change detected. Starting incremental compilation...

node_modules/@shopify/polaris/build/ts/latest/src/components/OptionList/OptionList.d.ts:2:58 - error TS2307: Cannot find module 'types' or its corresponding type declarations.

2 import type { OptionDescriptor, SectionDescriptor } from 'types';
                                                           ~~~~~~~

node_modules/@shopify/polaris/build/ts/latest/src/types.d.ts:2:61 - error TS2307: Cannot find module 'components' or its corresponding type declarations.

2 import type { AvatarProps, IconProps, ThumbnailProps } from 'components';
                                                              ~~~~~~~~~~~~

[9:12:35 pm] Found 2 errors. Watching for file changes.
```

The two imports here are not using relative paths unlike most others, and when I update those two files locally to import `'../../types'` and `'./components'` (I think it was), the type check completes without error.

My tsconfig.json is:

```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "jsx": "react",
    "moduleResolution": "node",
    "noEmit": true,
    "resolveJsonModule": true,
    "target": "ES2020"
  },
  "include": [
    "src/**/*"
  ]
}
```

## Specifications

- Are you using the React components? (Y/N): **Y**
- Polaris version number: **7.0.0**
- TypeScript version number: **4.3.5** (also tried with 4.4 and 4.2)
- Browser: **N/A**
- Device: **N/A**
- Operating System: Arch Linux

**Comment by irvinebroque** [comment]
Hit this too, looks like it happens because the tsconfig for this project allows anything in `/src` to be imported by name, without a path, so this doesn't get caught as a bug (say, in CI or on build):

https://github.com/Shopify/polaris-react/blob/755b3ceaee9d9aedb508c2cc95db64fad28aba09/tsconfig.json#L4

Offending code:

https://github.com/Shopify/polaris-react/blob/755b3ceaee9d9aedb508c2cc95db64fad28aba09/src/components/OptionList/OptionList.tsx#L2

Relative paths used elsewhere:

https://github.com/Shopify/polaris-react/blob/755b3ceaee9d9aedb508c2cc95db64fad28aba09/src/components/ActionMenu/ActionMenu.tsx#L4-L8

Proposed fix here: https://github.com/Shopify/polaris-react/pull/4542
