### ISSUE TITLE
TextField remaining characters count

### ISSUE THREAD

**Issue by jfangrad** [Shopify/polaris-react#491]
# Feature request summary

It would be nice if TextFields had the option to show the number of characters remaining when `maxLength` prop is set (see example below), or just the number of characters in the input if no `maxLength` is set.

<img width="626" alt="screen shot 2018-10-29 at 1 48 42 pm" src="https://user-images.githubusercontent.com/11445215/47675299-eeeb3b80-db8f-11e8-8cda-b2d52e4de4c1.png">

Perhaps a simple `showCharacterCount` prop can be used to enable/disable the character count being displayed.

## Rationale

It is quite common when building forms to have text input fields that are character limited. Simply setting a max length on the field means that the user has no visual feedback that they have run out of characters except for that when they continue to type characters are no longer added to the input.

This also means that users can't see how many characters they have remaining while trying to decide what to type.

---

## Possible Implementation
Because the `TextField` component uses the `Labelled` component to show the label and `action` (if it exists), my initial thought was to extend the `Labelled` component to optionally display the number of characters remaining in the `TextField`. But this does mean that `TextField` has to pass optional information about the character count (as well as whether or not to show the count) to `Labelled`.

Another implementation could be simply creating another component that wraps the existing `TextField` and displays the character count. I feel like this might need some interesting css though to get the count to line up properly and adjust its position for when a `label action` is also used (like below).

<img width="366" alt="screen shot 2018-10-29 at 3 46 39 pm" src="https://user-images.githubusercontent.com/11445215/47676052-eeec3b00-db91-11e8-8bc8-6ef1a29997bd.png">

**Comment by ry5n** [comment]
My instinct is to put the character count underneath the input. This accounts for multi-line textfields on small screens, where the label may scroll out of view as the person types, but they’ll likely still see the bottom of the field.

Right-aligning the counter makes sense; it would be nice to allow an optional description next to the character counter such as “characters remaining”.

In terms of interaction, the character counter is a kind of combination help text/inline error because its state is dynamic. I wonder if we could build a component that combines TextField and InlineError with some additional state management to do this?

**Comment by jfangrad** [comment]
@ry5n Your reasons for putting the counter below the input sound good to me. The optional description also sounds like a good idea.

As for your last thought, you are suggesting to create a whole new component, correct? If so what would you suggest this be called to convey the difference between it and the normal `TextField` component? I ask because I can't think of a good name that isn't to long.

**Comment by ry5n** [comment]
A new component is one possibility, but I’m not certain it’s the right choice. `TextFieldWithCounter`? `TextFieldWithCharacterCounter`?

Maybe your original suggestion would be better, with a single prop to enable the character counter. @danrosenthal what do you think here? Wrapper, or add a prop to the TextField API (or something else)?

**Comment by dpersing** [comment]
Just a note on AT support: We'll want to make sure the character count is wrapped in an ARIA live region so that the count can be conveyed dynamically. I think treating the count message as a Help text variant (via `aria-describedby`) would be good so that it's read while the user focuses on the field, but then the count should get read periodically via `aria-live="polite"` as it changes. We also might want to provide some additional text around the number so its meaning is clear.

Collections is currently using the help text pattern with "X of Y characters used" to give context, for example:

![X of Y pattern for remaining characters](https://user-images.githubusercontent.com/1462085/48794458-e1b4fe80-ecae-11e8-9a49-1f8d67613b2f.png)

The output might look something like this:
```
<label for="input-example">...</label>
<input type="text" id="input-example" aria-describedby="character-counter-example">
<span id="character-counter-example" aria-live="polite">X of Y characters used</span>
```

**Comment by jfangrad** [comment]
@dpersing Those are great point thanks!

Just thought I would show here what this would look like when error and help text are also present.

<img width="962" alt="screen shot 2018-11-29 at 4 20 26 pm" src="https://user-images.githubusercontent.com/11445215/49252767-df5f4c80-f3f2-11e8-8042-d31e20806bd2.png">

It can get a little busy but I suppose that can't be avoided and would only ever be in that situation in error states.

**Comment by dpersing** [comment]
>It can get a little busy but I suppose that can't be avoided and would only ever be in that situation in error states.

Agreed there's a lot there @jfangrad! Is there a case where the "X of Y characters used" would have additional help text, do you think? My main concern with putting a count far out on the right is that it might get missed by folks that are zoomed in or using magnification. I definitely think there's some wiggle room for placement!

**Comment by jfangrad** [comment]
@dpersing I don't think there would be any reason for there to be any additional help text. At least not that I can think of!

You make a good point with the magnification and I also think it is fine in either place. However I do think that putting it on the right would be more visually appealing 😃 but thats not the most important criteria.
