### ISSUE TITLE
[Link] Add support for data-primary-link

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react#6093]
The `data-primary-link` attribute is not supported on any of our linkable components, yet is required in order for the `IndexTable.Row` ~and `ResourceList.Item`~ to trigger click-through instead of row selection. This causes folks to have to use an `a` directly, which is confusing (see https://github.com/Shopify/polaris/issues/4138).

**Comment by fmoliveira** [comment]
Hello @chloerice ! I'm interested in working on this issue. Could you please help me clarify a couple of points before I begin?

1. The linkable components that I'm aware of are Link and Button, along with their Unstyled lower-level components. Is that all, or do we have any other linkable components that also need to support the `data-primary-link` attribute?

2. There seems to be another problem with the ResourceItem component. This component does accept click-through on a Link component, however, it also bubbles up to the ResourceItem component. The bubbled-up event causes unintended side effects depending on how the Link component is used. I've outlined these scenarios in the sandbox below, would you mind taking a look at them?

Sandbox here: https://codesandbox.io/s/proud-glitter-h5wbrq?file=/src/App.tsx

Should we ensure that only links with `data-primary-link` are clickable from inside a ResourceItem - effectively applying the same behaviour that we already have on IndexTable.Row? If the link does not have the data-primary-link attribute, then we should not be able to click-through it?

Finally, should I file a separate issue for this bubble-up problem? Or is it ok to investigate and include the fix on this ticket? There's a trade-off of complexity and time-to-ship, I'm confident that I can implement the data-primary-link prop as my first issue, but the bubble-up problem seems a bit more involved and I'd be more comfortable opening a separate issue for that – which I would also consider grabbing at a later moment.

What are your thoughts about both points?

Thank you very much in advance!

**Comment by chloerice** [comment]
Hi @fmoliveira! 👋🏽 

1. Yes, Link and Button 💯  (adding the support to UnstyledLink and UnstyledButton may be all that's needed to do that, I can't remember offhand if Link and Button inherit props from them) 

2. Hmmm I would definitely make a bug report issue for the ResourceList/ResourceItem funkiness. If you do end up diving in to investigate and end up finding the bug is more complex than you have time to take on, that's totally okay. Leaving a comment detailing your findings is super impactful and helps the next contributor pick up where you left off 😁.

**Comment by fmoliveira** [comment]
Sounds good, I'll open a separate bug report for the other problem.

I will start working on implementing support for data-primary-link and post back if I have any questions about their interfaces or anything else.

Thank you very much for the guidance, @chloerice !

**Comment by fmoliveira** [comment]
Weekly update:

- ✅  **Done:** Added prop to Link and Button with unit tests, added stories to IndexTable and ResourceItem.
- ⏳  **In progress:** Adding integration tests to `IndexTable.Row`.
- 🚫  **Soft-blockers related to this issue, both can be addressed later in any case:**
  - ResourceItem does not seem to support `data-primary-link`, and I also skimmed the file for similar keywords but couldn't find it. Do you have any pointers about it, @chloerice ?
  - The website examples cannot be updated yet because the site uses the npm published version of polaris. I will open a follow-up ticket to add them as soon as a new version is released.

I've also caught a few more potential bugs that I'm keeping notes about. I will dedicate some time this weekend to report all of them properly.

**Comment by chloerice** [comment]
Thank you for digging into this, @fmoliveira!! 🙌🏽  

> ResourceItem does not seem to support data-primary-link, and I also skimmed the file for similar keywords but couldn't find it. Do you have any pointers about it, @chloerice ?

I misspoke when referencing `ResourceItem` in this issue, as it relies on configuration (`url` and `external`) for linking through.

>The website examples cannot be updated yet because the site uses the npm published version of polaris. I will open a follow-up ticket to add them as soon as a new version is released.

Yes, that's correct 💯 The site pulls examples from the latest release, so `README.md` examples in any PRs you ship will update them in production when the new release is cut. They can be included with any changes you ship (no need to ship them separately).

[Here's more info on our current release process](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#releasing), but tl;dr: whenever a PR is merged to main, the auto-generated "Version Packages" PR gets updated with the changes and when merged auto-publishes a new release and a new PR titled "Version Packages" is created to prep the next release. (We release often, here's [the PR for the next release](https://github.com/Shopify/polaris/pull/6320) 😁)

**Comment by chloerice** [comment]
Here's the other issues we have related to `data-primary-link`:
- https://github.com/Shopify/polaris/issues/6091
- https://github.com/Shopify/polaris/issues/4345 
  - (Fix here, but needs a test https://github.com/Shopify/polaris/pull/4361)

**Comment by fmoliveira** [comment]
@chloerice Thank you very much for pointing me to all the details about the release process and data-primary-link! I will follow all these issues and see what else I can contribute since I'm already involved in this topic.

> The site pulls examples from the latest release

Wow, really!? I've just found this process on the script `parseComponents.mjs` under the website package and I'm again fascinated to see the level of investment in developer experience here, it is great to have this updated automatically! 😉 

By the way, I'm happy to be finally digging into Polaris and really enjoying the snappy developer experience overall! ⭐ 

Thanks again for your time, @chloerice !

**Comment by chloerice** [comment]
> By the way, I'm happy to be finally digging into Polaris and really enjoying the snappy developer experience overall! ⭐

Thanks so much for that feedback @fmoliveira!! We're happy to have you 😁 You can look forward to some cool improvements to DX in the future, we're invested in making it a clearer and smoother contribution experience from GitHub to your terminal 🤓

**Comment by fmoliveira** [comment]
> Thanks so much for that feedback @fmoliveira!! We're happy to have you 😁 You can look forward to some cool improvements to DX in the future, we're invested in making it a clearer and smoother contribution experience from GitHub to your terminal 🤓

Thanks so much for the warm welcome and the onboarding! Excited to see what happens next to DX in Polaris and Shopify in general 🚀  

From my comment above https://github.com/Shopify/polaris/issues/6093#issuecomment-1164360703 :
> I've also caught a few more potential bugs that I'm keeping notes about. I will dedicate some time this weekend to report all of them properly.

The bugs I was keeping notes about are very minor and only reproducible on Storybook, and I'm not sure if it's worth reporting them or if would just cause more noise - so I will at least reference them here to fill up the context from above. They are the same issues described as " 👾  Related bugs" on my PR.

- Clicking a Link or Button with dataPrimaryLink on the IndexTable stories fires the own link's onClick event twice. This can only be noticed if you remove the `url` prop the Link or Button, and look at the developer console for the `onClick` logs.
- On Storybook's Docs view, clicking the checkboxes of these two stories has no effect - it does not select any of the rows. This problem only happens in the Docs view and works fine on the default Canvas view, although it seems somehow related to data-primary-link because the checkboxes work fine for all the other stories in both views.

**Comment by mchemanishop** [comment]
@fmoliveira , I still got this issue: 
```
Clicking a Link or Button with dataPrimaryLink on the IndexTable stories fires the own link's onClick event twice. This can only be noticed if you remove the url prop the Link or Button, and look at the developer console for the onClick logs.
```
Do you have a workaround or something I could use?
