### ISSUE TITLE
[Pagination] Disable buttons trigger onPrevious/onNext when using the keys and render the tooltips

### ISSUE THREAD

**Issue by tleunen** [Shopify/polaris-react#668]
# Issue summary

3 things I noticed about the pagination, keys and disable state:

1. The tooltip is shown on disabled pagination buttons
2. When the tooltip appears on a disabled button, it's hard to hide it. Hovering out a normal button hide the tooltip, but it's not the case for the disabled button.
3. Triggering the key event triggers the previous/next callback, even if the button is disabled

![kapture 2018-11-22 at 15 13 38](https://user-images.githubusercontent.com/1972567/48920841-59c72400-ee69-11e8-9380-19fc78f2122f.gif)

## Expected behavior

- I'm not sure if 1. is expected or not. Having it or not could be valid I guess.
- Hovering out of the button should hide the tooltip though.
- Key presses should not trigger the callbacks if `hasPrevious`/`hasNext` is false (button disabled).

## Actual behavior

See issue.

## Steps to reproduce the problem

1. Use the codesandbox and play each bullet points in the summary

## Reduced test case

https://codesandbox.io/s/ywrxx3qp8j

**Comment by tleunen** [comment]
Looks like 3. will be fixed by https://github.com/Shopify/polaris-react/pull/643

**Comment by AndrewMusgrave** [comment]
Thanks for the issue @tleunen # 3 will be fixed in our next release. @sarahill do you have any thoughts on 1?

**Comment by sarahill** [comment]
It feels like a bug to have the tooltip show up if the button is disabled. I would lean toward not displaying the tooltip for disabled button since there is no action you can take.

**Comment by ruairiphackett** [comment]
The [CSS solution here](https://github.com/facebook/react/issues/4251#issuecomment-267004045) fixes # 2 if applied to the [disabled Pagination Button](https://github.com/Shopify/polaris-react/blob/master/src/components/Pagination/Pagination.scss#L151-L157):
```
.Button {
  &:disabled {
    pointer-events: none;
  }
}
```

I'm not sure if there's any scenario where we might need `pointer-events` on a `disabled` button though?

Forked sandbox with the fix for # 2: https://codesandbox.io/s/xoyqy6y5mw

**Comment by ruairiphackett** [comment]
I can put in a PR with the above if it is an acceptable fix.

**Comment by yourpalsonja** [comment]
@dpersing @AndrewMusgrave any thoughts on the above fix?

**Comment by dpersing** [comment]
>I'm not sure if 1. is expected or not. Having it or not could be valid I guess.
Hovering out of the button should hide the tooltip though.
Key presses should not trigger the callbacks if hasPrevious/hasNext is false (button disabled).

Agreed that the tooltip should disappear when hovering out. Since we're using tooltips to instruct users of the keyboard shortcuts, I like the idea of still showing the tooltip on hover, but this creates an inequitable experience for people who aren't using the mouse, so I'm inclined to say we should suppress tooltips on disabled buttons.

That however brings up a question about whether or not using those tooltips to instruct users about the keyboard shortcuts is the best way to provide that information. ([There are also more general concerns about single-key shortcuts.](https://webaim.org/techniques/keyboard/accesskey#poor)) Not sure who we'd talk to about this, but it might be good to consider folding the pagination shortcuts in to any larger keyboard shortcuts provided across the platform.

**Comment by dleroux** [comment]
@dpersing are you saying we should still show the tooltip on disabled buttons?

**Comment by dpersing** [comment]
@dleroux I am not in favor of showing tooltips on disabled buttons, since they can only be accessed by mouse users, and users won't expect any interaction on disabled controls. This also doesn't provide any support for keyboard and touch users.

Instead of relying on tooltips to provide instructions in this scenario, I think it would be good to look at overall keyboard shortcuts and provide a standard in the platform-wide keyboard shortcut instructions. Having keys that do pagination in some cases and not others will cause confusion, and allowing folks to assign their own causes fragmentation in the experience.
