### ISSUE TITLE
[Page] Access to Page layout while using embedded app

### ISSUE THREAD

**Issue by michelleyschen** [Shopify/polaris-react#669]
I love the polaris `Page` layout and would love to use this throughout my app to display header, breadcrumbs, primary + secondary actions.

<img width="812" alt="screen shot 2018-10-22 at 12 09 59 pm" src="https://user-images.githubusercontent.com/1610169/47303999-6c90d380-d5f3-11e8-8fb8-7ec00957a814.png">

However, because the application is an embedded app (and I do need some app-bridge functionalities ie. modal, toast), the `Page` component default to embedded app view that add breadcrumbs in the same line with app name.

<img width="1116" alt="screen shot 2018-10-22 at 12 14 09 pm" src="https://user-images.githubusercontent.com/1610169/47304233-03f62680-d5f4-11e8-9886-b6e337ca1457.png">

I have temporarily resolved the issues by copy & pasting the current `Page` component and calling 
`this.context.easdk.Bar.update({icon: 'icon_url'});` myself.

Ideally, I can also pass the icon once as part of `AppProvider`, and have this icon persist throughout the entire app.

**Comment by michelleyschen** [comment]
moved from https://github.com/Shopify/polaris-react-deprecated/issues/2468
cc @tmlayton

**Comment by danrosenthal** [comment]
👋 Hey @michelleyschen, thanks for the issue. As with other feature requests, I'm going to close this issue and allow voting on the original comment using the 👍 emoji to indicate support for making this change. We'll evaluate the demand for such a feature and prioritize accordingly.

Also, I'd like to loop in @davekilljoy and @markiiikram as they may have opinions on whether this is something the App and Partner Platform team would like to see done.

**Comment by jennaleeb** [comment]
Oh hai @danrosenthal , @davekilljoy and @markiiikram ! We were also surprised by the removal of this title. Were previously using it and then upgraded our polaris to use app-bridge directly and it went away. Thoughts?

**Comment by markiiikram** [comment]
Prior to Polaris v3 there was an Embedded page component. I added it in this PR [Add embedded page section](https://github.com/Shopify/polaris-react-deprecated/pull/956)

**Comment by michelleyschen** [comment]
This issue may have to re-write. Because really I documented an approach, where there may be other things we can do here rather than separating the component. 

Mainly the question here is: if an embedded app want to use the visual style of `Page`
<img width="812" alt="screen shot 2018-10-22 at 12 09 59 pm" src="https://user-images.githubusercontent.com/1610169/47303999-6c90d380-d5f3-11e8-8fb8-7ec00957a814.png">
but also secondary navigation.

Is this possible to do in Polaris without forking?

**Comment by markiiikram** [comment]
@michelleyschen From my understanding there is no way to use the standalone page component inside an embedded app. I think the approach would be as Dan said, for us to vote on the original comment for Polaris to make a change. Maybe everyone on your, my and @jennaleeb's teams could up 👍? /shrug

**Comment by jennaleeb** [comment]
Re-opening this issue after chatting IRL with @danrosenthal and @markiiikram !

Historically, the embedded page was different from the polaris/core-web component due to some technical constraints and design decisions.

Given the need to support 1P apps (e.g., those developed by Shopify), it would be great if, when possible, components in embedded apps had parity whenever possible. It also makes dev life less confusing when devs/designers are searching for components to use but then are not _actually_ available, or, even worse, are _slightly_ different.

Going to shop this around other projects and see if the issue of the `<Page/>` component is affecting anyone else.

On a higher level note, given A&PP's focus on 3P developers, and other teams developing within core, there is a gap in understanding of who owns the full stack used by 1P Shopify app developers.

**Comment by danrosenthal** [comment]
Removed the `Feature request` label as this is a more complex problem than a simple feature request. Thanks @jennaleeb for the context. We encourage all first party app developers within Shopify to weigh in on this problem here.

**Comment by jennaleeb** [comment]
I am a bit confused of what the Page component actually renders, because IIRC when I switched over to app provided through polaris, not directly app-bridge, the header, secondary nav and `By Shopify` stuff still remained. It was just the title within the Page itself that disappeared.

**Comment by davekilljoy** [comment]
Right I understand, I thought we wanted to replace the App Bridge header with the `Page` component vs having the `Page` coexist with the App Bridge header.

**Comment by jennaleeb** [comment]
Ah ok, understand the confusion! No, just about the way it renders within the page.

**Comment by keyfer** [comment]
Chiming in here from another 1-P app developer perspective.

When we started building our app, we defaulted with the embedded app view that adds breadcrumbs in the same line with app name, without realizing there was a secondary option. It is a bit of an interesting disconnect having two different page layouts. I would love to see parity between these `Page` components, but also having the option to choose between each option would be nice

**Comment by michelleyschen** [comment]
I put up an PR for a possible solution
https://github.com/Shopify/polaris-react/pull/695

**Comment by vividviolet** [comment]
@jennaleeb It looks like the title is there at the top next to the app name instead of being rendered within the page
![image](https://user-images.githubusercontent.com/29458473/49247498-66a5c380-f3e5-11e8-9a49-99a5b80fc365.png)

I don't think this has been mentioned but App Bridge does not render Pagination. @tmlayton, do you know what happens when someone uses the Page component with Pagination? I think the expected outcome is that pagination will be rendered inside the app page.

**Comment by vsumner** [comment]
We ran into this issue for Flow. 

When I added the api key to `AppProvider` which enabled appBridge for the Page component the layout "broke" as it switched to using AppBridge for rendering.

My current workaround for this problem was to create a `AppBridgeProvider` that passes `appBridge` on context so I can use AppBridge functionality in other places. 

I don't want to use this long term but it makes it so that I can use app-bridge Actions (Redirect, History).

```
 <AppProvider linkComponent={Link as LinkLikeComponent}>
    <AppBridgeProvider apiKey={apiKey()}>
        <App />
    </AppBridgeProvider>
</AppProvider>
```

**Comment by jennaleeb** [comment]
@vividviolet if you look at the [first image](https://github.com/Shopify/polaris-react/issues/669#issuecomment-442874129) is also has the title at the top next to the app name.

**Comment by vividviolet** [comment]
@jennaleeb Yeah, I see the title in both screenshots. I think the title was actually provided twice before - through the easdk and then again on the Page component. Were you manually calling the easdk previously to set the title?

**Comment by michelleyschen** [comment]
So the `Page` component render two things.
The `Header` component and some css that setup the page margin.

When the `Page` component see the app-bridge context (if you have `apiKey` prop in `AppProvider`), instead of rendering `Header`, it passes the title, breadcrumbs and actions to app-bridge to have those things render inside Shopify admin top bar.

Out of all the components that interact with app-bridge. This is the only one have has such drastic visual difference. I have set up https://github.com/Shopify/polaris-react/pull/695 so you can pass two props to opt out of this visual difference.
