### ISSUE TITLE
[TextContainer] Missing top margin on Polaris components within TextContainer

### ISSUE THREAD

**Issue by JenGreatrix** [Shopify/polaris-react#670]
# Issue summary

When upgrading to Polaris 3, `<DisplayText />` inside a `<TextContainer />` no longer adds top margin.

## Expected behavior

`<DisplayText />`(and other Polaris components) inside a `<TextContainer />` should have a top margin when there is more than one. 

## Actual behavior

![](https://screenshot.click/22-55-9f38u-mx9lv.jpg)

## Steps to reproduce the problem

1. add multiple `<DisplayText />` components inside a `<TextContainer />`

## Reduced test case

https://codesandbox.io/s/ov32248my5

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.1.1
- Browser:
- Device: 
- Operating System:

**Comment by dleroux** [comment]
Looks like we are relying on the order of CSS here :(

TextContainer uses the following CSS

```
.TextContainer > * + * {
    margin-top: (spacing($spacing));
  }
```

Since `*` has zero specificity, any styles applied to the children that appear after this selector will take precedence.

A possible solution would be to wrap the children in sub-component that would handle the styling.
