### ISSUE TITLE
Flash.Action.SHOW is causing an APP::ERROR::INVALID_ACTION error

### ISSUE THREAD

**Issue by jasonbuehler** [Shopify/polaris-react#729]
# Issue summary

When I dispatch a Flash.Action.SHOW to a flash notification on my embedded app I get an APP::ERROR::INVALID ACTION. 

## Expected behavior

I should see a flash notification and not get a client error. 

## Actual behavior

I get the following error:

<details>
t {name: "AppBridgeError", message: "APP::ERROR::INVALID_ACTION", action: {…}, type: "APP::ERROR::INVALID_ACTION", stack: "AppBridgeError: APP::ERROR::INVALID_ACTION"}
action:
action:
group: "Toast"
payload: {id: "a3b30a7e-1a49-4514-b1bd-4d57b729adac", duration: 3000, isDismissible: undefined, isError: undefined, message: "Success"}
type: "APP::TOAST::SHOW"
version: "1.0.0-1"
__proto__: Object
message: "Unknown or unsupported action group"
type: "APP::ERROR::INVALID_ACTION"
__proto__: Object
message: "APP::ERROR::INVALID_ACTION"
name: "AppBridgeError"
type: "APP::ERROR::INVALID_ACTION"
stack: "AppBridgeError: APP::ERROR::INVALID_ACTION"
__proto__: Error
</details>

## Steps to reproduce the problem

1. Using app bridge, create a new flashNotice
2. Dispatch the Flash.Action.SHOW action to the flash notice

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.2.1
- Browser: Chrome
- Device: Laptop
- Operating System: OS X

**Comment by tmlayton** [comment]
@jasonbuehler thanks for the issue. If you are using Polaris React, the `<Toast />` component will handle delegation to app bridge on mount when in an embedded context as long as you pass your API to the `<AppProvider />`.

If you are creating your own app bridge instance outside of Polaris React, check the version. I _think_ as of 0.8.0 they changed Flash -> Toast.

Otherwise, for issues specific to app bridge, please direct them to https://ecommerce.shopify.com/c/shopify-apis-and-technology for now, although they will be making their repo public in the future.

I’m going to close this issue for now, feel free to reopen if using `<Toast />` is causing errors.

**Comment by jasonbuehler** [comment]
Hey @tmlayton , quick question - is this behavior going to be fixed at all moving forward? I find it a better pattern for showing things like a flash message to use the app bridge in the context rather than having to conditionally insert a component in the render tree and/or pass the triggering function down through the props to the child components. I would love to be able to just use app bridge to display a flash message (as well as to use the rest of the functionality in app bridge).
