### ISSUE TITLE
[polaris.shopify.com] Side navigation adjustments

### ISSUE THREAD

**Issue by tracytees** [Shopify/polaris-react#7486]
Currently the left menu navigation provides 2 different interactions: 

1. User clicks on section title > brought to an overview page with information
2. User clicks on the `+` beside a section title and an accordion opens

When we begin to add more pages in these sections, users who click on the `+` may not discover there is information in the section title itself.

**Proposed idea:** 

- The section title and the `+` should have the same interaction (expand the menu)
- There should be an overview page for each section so any general information is not hidden

**Comment by martenbjork** [comment]
I'm open to this! The most important thing is that we have consistency. Items in the nav should always behave in the same way. (`.dev` fails at this and sometimes have overview pages, sometimes not — it's confusing!)

Worth talking about: What about groups that doesn't have child items, like `What's new`, `Icons` and `Sandbox`? It would be awkward to force a `Overview` page on them.

Anyways, down to jam if you want to prototype this!

**Comment by SeanyB** [comment]
I don’t this we should add separate Overview pages “under” the section names for a couple reasons:
- It creates a redundancy where every expanded list is a little larger because we have this extra row.
- The Overview page would be listed alongside pages that aren’t truly its “siblings” - really, it’s the parent providing context on the children.

I think we should keep our current paradigm of having the parent link have its own page when you select it.

I imagine that most folks will accidentally click on the large target of the name and see a parent page has content at some point, so I don’t think we risk having users only clicking + and never learning that we provide content for those parent links.
