### ISSUE TITLE
Audit usage of focus ring across components

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#7595]
Refs: #7585

The focus rings purpose is to show when users are keyboard navigating. It is showing up on multiple components without the users using their keyboard.

Audit the components and remove the focus ring unless the element receives keyboard input.

Example with ActionList:
![Screenshot 2022-11-01 at 7 50 09 AM](https://user-images.githubusercontent.com/19199063/199262594-b1e74951-7b6b-48ba-a785-d383e0aaf977.png)

**Comment by gwyneplaine** [comment]
## Focus ring migration care package
**Contributors: @gwyneplaine **
**Purpose:** The migration project wrapped up and we were not able to complete the focus ring migration. This documents our rationale and learning through this migration.

In November 2022 we attempted to migrate the undocumented focus-ring SCSS mixin to two new tokens. The focus-ring mixin is used [255 times in shopify/web](https://grokt.shopify.io/results?q=r%3AShopify%2Fweb+%22%40include+legacy-polaris-v8.focus-ring%22) and [127 times in shopify/polaris](https://grokt.shopify.io/results?q=r%3Apolaris+focus-ring&scope=public). Running this migration on the `app` folder alone, netted us a css code reduction of 2.2%, down from 5.2735mb to 5.156283mb. We expect this to be a larger percentile as we run it on more of the web codebase. 

Despite these clear performance wins, rolling out this migration surfaced issues that tanked our confidence in being able to run this migration safely. These issues are innately tied to the CSS cascade and how teams were using or overriding the styles from focus-ring to reduce their total CSS output. Replacing these mixins caused these edge cases to break. We also noticed that Safari did not support border-radius with outline, though this has been resolved in the latest[ preview release of Safari](https://webkit.org/blog/13575/release-notes-for-safari-technology-preview-157/). 

Problems at a high level: 
* The focus ring shows when users were not focusing elements. This created an inconsistent pattern and usage across the admin.
* The focus ring is not documented and copy-pasted across the admin.
* The focus ring mixin CSS is overridden or overrides something else in the cascade
* The focus ring CSS contains 13 properties which can be reduced to two
* Migrations at scale are unachievable as we have no safe base case due to the CSS cascade 

If you would like to understand these issues more deeply, see the Important Details section below. 

-----------------
### Important details

The replace-focus-ring migration in the polaris-migrator package aims to replace the focus-ring mixin with a terser outline declaration with associated focus-ring tokens. The PR for this migration lives [here](https://github.com/Shopify/polaris/pull/7496), and the migration has been run in a POC PR on web [here](https://github.com/Shopify/web/pull/77134). 

The proof of concept PR is not something we should merge into main, but aims to accomplish the following things:
Validate the focus-ring tokens included in the installed snapshot release in this PR
Validate removing usages of the legacy-polaris-v8.focus-ring in favor of outline and outline-offset declarations with focusRing token values (more on this later)**
Act as an artifact for pursuing and resolving the ongoing discussion around focus-states in the admin as per the following [issue](https://github.com/Shopify/polaris/issues/7595) and [slack thread](https://shopify.slack.com/archives/C4Y8N30KD/p1667242750874599)

**Previously the focus-ring mixin evaluated to the following css (in the base case)
```css
   position: relative;
    &::after {
      content: '';
      position: absolute;
      z-index: 1;
      top: $negative-offset;
      right: $negative-offset;
      bottom: $negative-offset;
      left: $negative-offset;
      display: block;
      pointer-events: none;
      box-shadow: 0 0 0 $negative-offset var(--p-focused);
      transition: box-shadow duration(fast) var(--p-ease);
      border-radius: calc(#{$border-radius} + #{rem(1px)});
    }
```
The proposed migration in this PR resolves this down to the following lines
```css
outline-offset: var(--p-focusRing-offset-1);
outline: var(--p-focusRing-base);
```

This is a significant reduction in css, if we consider the number of times this mixin is presently called in the web codebase. Just running this migration over the app folder, has netted us a total bundle size reduction of 2.2% (roughly 130kB of css), we're expecting this number to be more significant if we were to run this over the entirety of web. 

However due to significant variance in how the focus-ring mixin is being invoked in web, there is at the moment very little assurance that we can run this migration successfully without some code breakage in web. Outlined below are the reasons for this. 

#### `border-radius`
The focus-ring mixin, presently appends an `:after` pseudo-element to its call-site with an associated border-radius property. This is done predominantly because at the time `outline` did not respect the set border-radius. As most browsers now support an outline property that respects border-radius, an assumption we've formed in the present migration strategy is that we can and should rely on a `border-radius` being set on the class or parent class where the `focus-ring` mixin had been invoked, such that our migration should only need to worry about setting the correct `outline` and `outline-offset` properties. 

This assumption holds true for many cases, such as in [ReportsIndexList.scss](https://github.com/Shopify/web/blob/701abfafc8b40bd60aafb587ef63b4307b61e53f/app/sections/Analytics/ReportsIndexList/ReportsIndexList.scss#L63) (note how a border-radius is set despite the border being set to none), however falls short in other cases such as [ViewReports.scss](https://github.com/Shopify/web/blob/701abfafc8b40bd60aafb587ef63b4307b61e53f/app/sections/Analytics/ReportViewer/components/CustomerCohortReport/components/ViewReport/ViewReport.scss), where a border-radius isn't set. With the current available context in mind, coming up with a heuristic that results in 0 code breakages from running this migration is a non-trivial task due in part to:
No definable base case (both ReportsIndexList and ViewReports appear to be legitimate use cases) 
It being impossible to guarantee accurate detection of a relevant border-radius property on running the migration (sass has many ways for us to inject styles, and many of them are difficult to impossible to detect without running and evaluating the resultant CSS). 
I've written a lengthy description of why this isn't a trivial problem [here](https://github.com/Shopify/polaris/pull/7496#issuecomment-1301621388). Until we can either narrow down to a definitive base case, or figure out a way to mitigate or accurately detect border-radius declarations at the call-site of the focus-ring mixin invocation, this migration is not one that we should confidently run and merge into web. 

#### `outline` 
Similar to the border-radius case above, certain usages of `focus-ring` are preceded or succeeded by an `outline` declaration. Often this is `outline: 0` to reset the outline such that the focus-ring styles don't overlap with existing outline styles. However at other times such as in [`ReportsListItem`](http://app/sections/Analytics/ReportsIndexList/components/ReportsListItem/ReportsListItem.scss) a transparent outline with a particular thickness is declared in order to add more space between the applied `focus-ring` `:after` pseudo element and the root element the style is applied to. The latter case happens rarely enough for us to manually resolve this value with our migration. The former however falls under the same complexity constraints as our border-radius case. 

Moreover, assuming we overcome these barriers, there is one more downside; Temporary reduction in UX for Safari users, as the outline property presently doesn't respect border-radius in Safari. See the figures below

Safari button with outline:
<img width="151" alt="Screen Shot 2022-11-04 at 5 09 12 pm" src="https://user-images.githubusercontent.com/12119389/201794135-4f75fbec-e32d-4681-ad90-935a8f7502d6.png">

Non Safari button with outline:
![Screen Shot 2022-11-04 at 5 07 26 pm](https://user-images.githubusercontent.com/12119389/201794140-8f1512c2-cb34-4767-be43-84d82385868c.png)

[This is an active bug for Safari, and likely to be resolved soon](https://bugs.webkit.org/show_bug.cgi?id=20807). Moreover focus outlines are hidden behind a feature flag in Safari by default. That said, this stipulation doesn't matter if we're using focus-ring styles for behavior other than focus. 

--------------------
### Normalizing focus-ring style usage
Permeating all of the concerns we've touched on above, is uncertainty around how focus-ring is used in web admin today. As per the following [issue](https://github.com/Shopify/polaris/issues/7595) and [slack thread](https://shopify.slack.com/archives/C4Y8N30KD/p1667242750874599) it appears that we now have multiple patterns in the wild leveraging the focus-ring styles for non-standard usages outside of the context of an input element with browser focus. (the original intent of the focus-ring styles). Setting up firmer constraints around how focus-ring should be applied in web, should help us: 
Mitigate the Safari issue by reducing the number of focus-ring styles applied in contexts not pertaining to browser focus on input elements 
Create more determinism around focus-ring usage, such that we have a higher confidence that running the focus-ring migration won't result in code breakages in web. 

--------------------
### Next Steps: 

- [ ] Check if Safari supports outline border radius
- [ ] Validate and ship focus-ring tokens. 
- [ ] Polaris-react
  - [ ] Audit Polaris component usage of focus-ring
  - [ ] Remove focus ring that is shown when elements are not focused
  - [ ] “Migrate safely” the focus-ring mixin to the new custom properties
  - [ ] Get UX feedback for the usability/experience changes
- [ ] Web
  - [ ] Audit Web component usage of focus-ring
  - [ ] Remove focus ring that is shown when elements are not focused
  - [ ] “Migrate safely” the focus-ring mixin to the new custom properties
  - [ ] Get UX feedback for the usability/experience changes

**Comment by sophschneider** [comment]
Just an fyi, I [replaced](https://github.com/Shopify/polaris/pull/8780) the Polaris `Banner` focus ring with `outline` because there was a weird horizontal scrolling bug with the `:after` positioning. 

Making this list so we can keep track of bespoke focus rings in polaris-react:

### List of custom focus rings
* Banner
* ....
