### ISSUE TITLE
Component test utilities should be exported.

### ISSUE THREAD

**Issue by sgargan** [Shopify/polaris-react#769]
# Feature request summary
I'd like to be able to use the utilities like mountWithAppProvider, trigger etc,  from test-utilities to test my own components. Though the types are available I've not been able to import the functions and I don't think they're being exported by polaris.

## Rationale function
 Expose the test functions so they can be used to test components in projects using polaris. Add some documentation explaining how to use these in tests.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by dleroux** [comment]
Hi @sgargan thank for submitting this Issue. 

One reason we don't currently export these is that we don't want to increase the bundle size for things that aren't required for Polaris. We do export `createPolarisContext` which allows you to create your own `mountWithAppProvider`.  Also should we ever decide to change our testing framework we wouldn't want to break your tests. 

Since this is sort of like a feature request I will close and let you and other people upvote if you feel you'd still find this useful.
