### ISSUE TITLE
Pattern detail page - Figma visual design tweaks

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react#7949]
This issue captures ideas for adjustments to the visual design of the Pattern detail page as a whole. These are suggestions, but a designer should look at this carefully to decide the best approach.

- [x] The **Useful to know** images visually blend together on the page. Can we prevent this, perhaps with a border around them or some other treatment?
- [x] The **Related resources** cards appear **too** prominent at the bottom of the page. Can we reduce their prominence with a change to their visual treatment? Do they need images for them?
    - They are larger than the cards we use on the Components and Patterns index page, but that doesn't feel right because these are useful links that a reader _may_ want to use, which isn't as primary a use case as finding a component or pattern from the index page.
    - At their current size, they also visually compete with the main page content.
- [x] As per the suggestion in https://github.com/Shopify/polaris/issues/7966, adjust the page padding in the Figma design to match the current Polaris website padding.

**Comment by bernardojoaogarcia** [comment]
Pattern page widths, paddings etc, are now adjusted. After completing this ticket I will move the design to a "most recently updated" page in our file.

**Comment by johanstromqvist** [comment]
Regarding `related resources`. @selenehinkley and I spoke about this before the break and both thought that a simple unordered list would be a better short term solution.

Regarding `Useful to know` and the "blending issue". There are a few factors to this issue:
1. UI illustrations continue past the image boundaries, creating a sense of continuation
2. The contrast between image background and page background is very low, causing a lack of boundary. This is further reduced by the tab background color.
3. The large scale of the images causes the rhythm and focus of the page to break.
4. The spacing between the images vertically is smaller compared to the spacing between each copy + image pair, which makes us perceive the images as grouped vertically.
The result is a lot of smudge and unclear grouping. Adding a border could make the image boundary clear, but it would be great to see if we can find other somewhat quick fixes that address some of the root problems.


### Continuation past boundary
![Image](https://user-images.githubusercontent.com/38329124/210906781-4a8a14a3-d21f-4572-b02b-bc7c2fb2eb5f.png)

### Low contrast
![Image](https://user-images.githubusercontent.com/38329124/210906992-e238fbb5-7b1a-401c-9192-63a18d5aad05.png)

### Variable scale
![Image](https://user-images.githubusercontent.com/38329124/210907069-ed47afd7-5029-42b8-afaf-4ddb83129621.png)

### Spacing
![Image](https://user-images.githubusercontent.com/38329124/210906950-dfadf5fd-c49a-4131-9414-8d6e31501f1c.png)

**Comment by bernardojoaogarcia** [comment]
**Update:** "Useful to know" visual contrast issues and "Related resources" overpowering visual prominence have been completed and addressed. Had a quick meet with @SeanyB and @johanstromqvist to review these visual changes, and they were approved. Regarding the Pattern page's padding and content alignment, I've attached 2 images to compare and contrast the alignment that we currently have in our staging prototype vs. an alt alignment, which lends optimal alignment to the page's content rather than the open tab container. 



![Image](https://user-images.githubusercontent.com/107587671/211668564-094156a7-00c4-4c6a-8b31-2bf23a6dd90c.png)
![Image](https://user-images.githubusercontent.com/107587671/211668565-e628a752-578b-414b-9f27-171177476d7f.png)

**Comment by johanstromqvist** [comment]
Thanks @bernardojoaogarcia! 

My understanding of the above padding suggestions is
- The first suggestion conforms to what we assume is the preferred implementation technically. The tradeoff is that tabbed content is indented and has less horizontal space compared to non-tabbed content on other pages.
- The second suggestion optically aligns all content across all pages, but may have implications on layout because it may need a negative margin or similar, and thus breaking technical layout conventions.

The preferred solution from a design POV would be number 2. Next step would be to get input from @jesstelford and @ChanChar.

**Comment by SeanyB** [comment]
Closing this issue as done. I've captured all of the engineering tasks in #7994, #8055, #8056, and #8057.
