### ISSUE TITLE
[polaris.shopify.com] Add the migration platform documentation to `/tools`

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react#8070]
### Open questions
- Should the docs be a single file? Routes per version/upgrade guide? Some other IA?

**Comment by SeanyB** [comment]
> Should the docs be a single file? Routes per version/upgrade guide? Some other IA?

My initial take would be a page that provides all of the explanation and installation instructions, followed by separate pages for each version upgrade guide so that we don't end up with a single massive page.

We can ship with 70-80% confidence in an approach and then ask for feedback from some devs.

**Comment by sam-b-rose** [comment]
@chloerice, can we consider this closed? Looks like this is live https://polaris.shopify.com/tools/polaris-migrator

**Comment by sophschneider** [comment]
@samrose3 Finished this in https://github.com/Shopify/polaris/pull/8087 but I didn't separate the migrations into separate pages. So if that work is still required I'd leave this open?

**Comment by sam-b-rose** [comment]
Good point. I think matching a similar way the Stylelint coverage rules are displayed would be good. Let's keep it open 👍 ty!
