### ISSUE TITLE
Is there a way to get the type of the original component in an linkComponent handler?

### ISSUE THREAD

**Issue by gerwinbrunner** [Shopify/polaris-react#838]
# Issue summary

I mapped a simple CustomLinkComponent in the <AppProvider> as [explained in the readme](https://github.com/Shopify/polaris-react/blob/176af463886887971c46361522ccfa6461976fa8/src/components/AppProvider/README.md#with-linkcomponent).

This works, for <Link> and for <Button> 

## Expected behavior

In the CustomLinkComponent I want to be able to know what the original component was
and have all the props of that component at hand.

## Actual behavior

In the CustomLinkComponent I have no way of knowing if the original component as a Link or a Button. So this breaks some button and makes them to regular links. 
Also not all props are passed down. i.e. primary on button, etc...

## Steps to reproduce the problem

1. Use the [readme](https://github.com/Shopify/polaris-react/blob/176af463886887971c46361522ccfa6461976fa8/src/components/AppProvider/README.md#with-linkcomponent) to create a CustomLinkComponent
1. add a Link and a Button in your test app and style them (i.e. button => primary)
1. see that both are rendered the same

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.4.0
- Browser: Chrome Version 71.0.3578.98
- Device: Mac
- Operating System: OSX

**Comment by solonaarmstrong** [comment]
Hi @gerwinbrunner 👋 Thanks for opening this issue. I am re-creating this and I will respond further...

**Comment by solonaarmstrong** [comment]
Would you be able to provide an example of your code in a [Sandbox](https://codesandbox.io/s/q82mlq0m26)?

**Comment by AndrewMusgrave** [comment]
👋 Would you mind helping me understand the why you need to know the root component? Possibly a code sample?

**Comment by yourpalsonja** [comment]
@gerwinbrunner any answer to the question above?

**Comment by nicklozon** [comment]
I have the same issue - I'm using React Router, so I used the linkComponent on the AppProvider so the React Router Link component is used in place of the standard [Polaris Link](https://github.com/Shopify/polaris-react/blob/c4006b3ed00223f8e81b26450cc5e8147b2f0ed0/src/components/Link/Link.tsx) component.

There are instances where the React Router Link is not desired - linking outside of the React application, or using the ```external``` prop on the Polaris Link component to open a new tab. The problem is once you set the linkComponent on the AppProvider there is no way to use the original Polaris Link component.

https://github.com/Shopify/polaris-react/blob/c4006b3ed00223f8e81b26450cc5e8147b2f0ed0/src/components/UnstyledLink/UnstyledLink.tsx#L26

I believe the linkComponent prop was introduced so custom client side routers would work with Polaris components. To me it makes sense to only apply the linkComponent when the Polaris Link is NOT external, though I can't say for certain this wouldn't break some use cases.

```js
if (polaris && polaris.link && !external) {
```
