### ISSUE TITLE
Toast isn't being displayed inside AppProvider if api_key is specified

### ISSUE THREAD

**Issue by ice-lenor** [Shopify/polaris-react#862]
# Issue summary

I'm trying out [this Toast example](https://polaris.shopify.com/components/feedback-indicators/toast) from Polaris documentation. I am adding it to an embedded app.

The problem is that the toast is not showing altogether, iif I specify `apiKey={apiKey}` in the `AppProvider` wrapper.

```
      // When apiKey is specified, Toast is NOT being shown
      <AppProvider apiKey={apiKey}>
          <Frame>
            <Page title="Toast example">
              <Button onClick={this.toggleToast}>Show Toast</Button>
              {toastMarkup}
            </Page>
          </Frame>
      </AppProvider>
```

Without `apiKey` it works perfectly.

```
      // When apiKey is NOT specified, Toast is being shown fine
      <AppProvider>
            ...the rest is exactly the same
      </AppProvider>
```

When it doesn't work (with `apiKey` specified), I don't see any warnings in the console, and nothing else suspicious is happening, the whole app with other Polaris components seems to work well.

## Expected behavior

When I have a toast inside the `AppProvider` with `apiKey` specified, toasts should be displayed in my app. As well as without `apiKey`.

## Actual behavior
Toasts are not being displayed in my app when I have `apiKey` specified in `AppProvider`.

## Steps to reproduce the problem

1. Take the [toast example](https://polaris.shopify.com/components/feedback-indicators/toast) from the Polaris documentation.
1. Add it to the embedded app.
1. Open the app as embedded app in Shopify.
1. Click on "Show toast" button.
1. => Toast works.
![image](https://user-images.githubusercontent.com/5493050/51076418-711bd400-1698-11e9-9ceb-75c192b3cfd7.png)

1. Now, change `<AppProvider>` to `<AppProvider apiKey={your_apiKey}>`.
1. Reload the app page.
1. => Toast is not being shown.

![image](https://user-images.githubusercontent.com/5493050/51076416-6a8d5c80-1698-11e9-9e38-e2f9339ac392.png)

## Reduced test case
Here is my source code (please rename to App.js, of course).
[App.txt](https://github.com/Shopify/polaris-react/files/2752337/App.txt)

## Specifications

- Are you using the React components? (Y/N):
    - Toast
    - AppProvider
    - Frame
- Polaris version number:
    - "@shopify/polaris": "^3.3.0",
- Browser:
    - Chrome 71.0.3578.98 on Windows
- Operating System:
    - Windows 8

Thank you!

**Comment by ice-lenor** [comment]
Thank you for your reply, sam-cnet.

I'm using bridge 0.7.3.

1. I also thought frame was only for stand-alone apps, but the app breaks without it.

This is what happens if I have two AppProviders, and the innermost is without the apiKey, and I don't have a Frame, and the app is embedded:

```
      <AppProvider apiKey={apiKey}>
        <AppProvider>
            {page}
        </AppProvider>
      </AppProvider>
```

```
TypeError: Cannot read property 'showToast' of undefined
```
```
  16664 | var appBridge = props.polaris.appBridge;
  16665 | 
  16666 | if (appBridge == null) {
> 16667 |   context.frame.showToast(Object.assign({ <---------on this line here
        | ^  16668 |     id: id
  16669 |   }, props));
  16670 | } else {
```

And if I only leave one AppProvider with apiKey, and I don't have a frame (or if I do have it), the toast just doesn't appear at all.

So an AppProvider without an apiKey does need a frame, and it says so in the documentation - so this setup works well. This setup, however, is meant for standalone apps.

The embedded app scenario - a single AppProvider with an apiKey, no Frame - doesn't work for me.

2. I tried this setup with forceRedirect like you suggested - the toast doesn't show up neither in an embedded app, nor in standalone:

```
      <AppProvider apiKey={apiKey} forceRedirect={false}>
            {page_with_toast}
      </AppProvider>
```

I also tried this - and the toast is being shown in both variants:

```
      <AppProvider apiKey={apiKey} forceRedirect={false}>
        <AppProvider>
          <Frame>
            {page}
          </Frame>
        </AppProvider>
      </AppProvider>
```

If I remove forceRedirect from this last scenario, this will be my current setup. The standalone app redirects to shopify admin, shows up as embedded, and the toast works.

I hope it isn't too confusing :). Thank you once again.

**Comment by sam-cnet** [comment]
Not confusing. The first thing that comes to mind after reading is to go to your shopify partner dashboard > your app extensions > shopify admin tab > manage embedded app, then enable and disable “Embed your app”.

Sent from my iPhone

On Jan 19, 2019, at 4:55 AM, ice-lenor <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for your reply, sam-cnet.

I'm using bridge 0.7.3.

  1.  I also thought frame was only for stand-alone apps, but the app breaks without it.

This is what happens if I have two AppProviders, and the innermost is without the apiKey, and I don't have a Frame, and the app is embedded:

      <AppProvider apiKey={apiKey}>
        <AppProvider>
            {page}
        </AppProvider>
      </AppProvider>


TypeError: Cannot read property 'showToast' of undefined


  16664 | var appBridge = props.polaris.appBridge;
  16665 |
  16666 | if (appBridge == null) {
> 16667 |   context.frame.showToast(Object.assign({ <---------on this line here
        | ^  16668 |     id: id
  16669 |   }, props));
  16670 | } else {


And if I only leave one AppProvider with apiKey, and I don't have a frame (or if I do have it), the toast just doesn't appear at all.

So an AppProvider without an apiKey does need a frame, and it says so in the documentation - so this setup works well. This setup, however, is meant for standalone apps.

The embedded app scenario - a single AppProvider with an apiKey, no Frame - doesn't work for me.

  1.  I tried this setup with forceRedirect like you suggested - the toast doesn't show up neither in an embedded app, nor in standalone:

      <AppProvider apiKey={apiKey} forceRedirect={false}>
            {page_with_toast}
      </AppProvider>


I also tried this - and the toast is being shown in both variants:

      <AppProvider apiKey={apiKey} forceRedirect={false}>
        <AppProvider>
          <Frame>
            {page}
          </Frame>
        </AppProvider>
      </AppProvider>


If I remove forceRedirect from this last scenario, this will be my current setup. The standalone app redirects to shopify admin, shows up as embedded, and the toast works.

I hope it isn't too confusing :). Thank you once again.

**Comment by sam-cnet** [comment]
@ice-lenor I notice you're using app-bridge actions to create and open the Toast. Try something like below and see if you can get it to work.

```
<AppProvider apiKey={apiKey} shopOrigin={shopOrigin} forceRedirect={true}>
  <App />
 </AppProvider>
```

```
class App extends React.Component {
  constructor(){
    super();
    this.state = {
      showToast: false
    };
  }

  render(){
    <Page>
      {{showToast()}}
    </Page>
  }

  showToast(){
    if(someCondition) {
	return (
	  <Toast content="You toasted!" onDismiss={() => this.setState({showToast: false})} />
	);
    }
}  
```
Best of luck!

**Comment by ry5n** [comment]
@tmlayton Any chance you can look into this?

**Comment by marguskoiduste** [comment]
Are you sure your "App URL" matches the URL where the app is actually loaded from? I had exactly the same behavior, but it turned out there was a mismatch between the "App URL" and the origin of the postMessage the AppBridge was sending. Please see this issue: https://github.com/Shopify/polaris-react/issues/1332

**Comment by tmlayton** [comment]
👋 apologies for the delay in getting to this issue! @ice-lenor remove the `Frame` component, the frame is only for stand-alone apps not embedded.

Based on your shared `App.js` code, it should look like this:

```diff
import React, { Component } from 'react';
- import {Frame, Page, AppProvider, Toast, Button} from '@shopify/polaris';
+ import {Page, AppProvider, Toast, Button} from '@shopify/polaris';

class App extends Component {
  state = {
    showToast: false,
  };

  render() {
    const {showToast} = this.state;
    const toastMarkup = showToast ? (
      <Toast content="Message sent" onDismiss={this.toggleToast} />
    ) : null;

    // When apiKey is specified in AppProvider, toast is NOT being shown
    // When AppProvider doesn't have apiKey, toast works
    const apiKey = process.env.REACT_APP_API_KEY;
+  // Whatever you want to call this env variable and constant
+  const shopOrigin = process.env.REACT_APP_SHOP_ORIGIN;

    return (
-      <AppProvider apiKey={apiKey}>
+     <AppProvider apiKey={apiKey} shopOrigin={shopOrigin}>
        <div style={{height: '250px'}}>
          <link rel="stylesheet" href="https://sdks.shopifycdn.com/polaris/3.3.0/polaris.min.css" />
-          <Frame>
            <Page title="Toast example">
              <Button onClick={this.toggleToast}>Show Toast</Button>
              {toastMarkup}
            </Page>
-          </Frame>
        </div>

      </AppProvider>
    );
  }

  toggleToast = () => {
    this.setState(({showToast}) => ({showToast: !showToast}));
  };
}

export default App;
```
