### ISSUE TITLE
Modal Title - Vertical alignment

### ISSUE THREAD

**Issue by laranoell** [Shopify/polaris-react#868]
# Issue summary
The Modal title appears slightly mis-aligned, vertically. 

## Expected behavior
Title and close icon are vertically aligned

## Actual behavior
![image](https://user-images.githubusercontent.com/3307989/51145184-1f528580-1821-11e9-8159-15aaac4d556f.png)

## Proposed Change:
Bump margin-top up to 0.4rem (from 0.2rem)
![image](https://user-images.githubusercontent.com/3307989/51145234-3f824480-1821-11e9-93e5-eadd5368f043.png)

**Comment by ry5n** [comment]
I haven’t looked at this in depth, but it seems like we should fix this as proposed. My guess is the alignment is off because we want the icon to always line up with the first line of the title, and not be centered with the whole title if the text wraps.

I bet an improved implementation could get us there.

**Comment by sarahill** [comment]
I'm for the proposed change. Makes sense and feel like it keeps it cleaner. 👍

**Comment by sarahill** [comment]
Ah looks like this has been fixed!
