### ISSUE TITLE
Purpose of 'defaultSortDirection' & 'initialSortColumnIndex' props in datatable?

### ISSUE THREAD

**Issue by tabrez96** [Shopify/polaris-react#873]
# Issue summary

I have a data table which has some sorted data (order: ascending, column: 4). I pass 'defaultSortDirection as 'ascending' and 'initialSortColumnIndex' as 4. I could see a sort icon (caret up icon) which appears near the sorted column heading. When I click on the column header which is already sorted in ascending order, 'onSort' from data table gives me direction as 'ascending' again.

My case: I get the sortDirection from the url of the page. Whenever I sort, I make an API and get the data from server. In this case, I use 'defaultSortDirection' & 'initialSortColumnIndex' props of datatable. But these two don't actually serve the purpose I guess.

## Expected behavior

Expected behaviour of onSort method is to return the direction which is opposite to the defaultSortDirection (i.e, it should be respective of 'defaultSortDirection' & 'initialSortColumnIndex' props).

## Actual behavior

Currently, onSort method returns sorted direction as 'ascending' which is irrespective of the 'defaultSortDirection'. When I have given 'defaultSortDirection' as 'ascending',  I don't expect the onSort handler to return 'ascending' again (assuming I sort again with the same column of initialSortColumnIndex).

## Steps to reproduce the problem

A sample codesandbox for the issue: https://codesandbox.io/s/64lw642123

Here, on sorting the data with the column-4 (net sales), onSort method returns direction as 'ascending'. I expect it to respect the 'defaultSortDirection' & 'initialSortColumnIndex' props and return the direction onSort. So here, it should return 'descending' instead of 'ascending'.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.2.1
- Browser: Chrome
- Device: Macbook
- Operating System: OSX 10.14.2

**Comment by dleroux** [comment]
Thanks for bringing this up @tabrez96. We'll take a look.

**Comment by chloerice** [comment]
Hey @tabrez96, thanks for raising this! I've got a [PR up to fix this](https://github.com/Shopify/polaris-react/pull/918). 

To answer your question about the purpose of the `defaultSortDirection`, the prop allows developers control over the table's initial sort direction (which defaults to `ascending` if not set). What this prop does is set the icon of the sorted column and the table's accessibility labels to indicate the direction that the table data is initially sorted in. It does not update the sort direction. 

In your CodeSandbox the `defaultSortDirection` prop is reset every time a sortable column heading is clicked or keypressed. I don't think `defaultSortDirection` is something you'll want to change programmatically on every sort, because the sort direction reversing is handled internally for you (though I'm guessing the sandbox was doing that because this was not working it should be on first sorting the initially sorted column!).
