### ISSUE TITLE
<Sticky /> has wrong top bar offset breaking sticky IndexTable headings

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#8932]
**Parent issue:** https://github.com/Shopify/core-issues/issues/47324
**Raised by:** @andrewmusgrave @mrcthms @nickpresta 

Next steps:
- [ ] Investigate what caused this regression
- [ ] Investigate if a quick fix to `<Sticky>` is possible as the topbar height is set as 56px. This might not work as responsive views this value changes.
- [ ] If we cannot resolve this issue with a quick fix. It might be worth investigating if using CSS `position: sticky` could remove the `<Sticky>` component all together.

<details>
<summary>⚠️ Important context from slack</summary>

> We have lost the ability for table headings to stick underneath the top bar within admin.
> @marcthomas

> Someone raised this issues a little while back. From what I saw the topbar wasn't in the dom when the sticky manager was registering, so the offset was 0 pushing our elements under the topbar
> Polaris explicitly sets the topbar height at 56px, I wonder if it's easier to manually set the sticky offset rather than inspecting the dom elements? 
> @andrewmusgrave

> Mobile app webviews don’t have a topbar but definitely have sticky things (e.g. table headers). Also, any page that goes “full screen” and hides the topbar also suffer from this issue, I suspect.
> @nickpresta

> I'm deep, deep, deep down various rabbit holes with this, but I've narrowed it down a little. Basically, there are three calls to the Polaris AppProvider, two of which come from the SkeletonFrame component and work as expected, and the third initialization comes from app/foundation/Polaris/Polaris – and it's this one that is causing the issue. > I believe that either the PolarisFrameWrapper or the app/foundation/Frame/Frame has some asynchronous code causing the <Frame> component from Polaris to not be present when the <AppProvider>  mounts.
> @marcthomas

> Is there a reason we can’t use CSS sticky?
> I am curious why rendering is causing problems with sticky positions :thinking_face:
> @alexpage

> I don’t remember the specifics anymore, but I think we had to implement JS sticky in Polaris due to old browser support and issues stemming from position: sticky having frustrating quirks about when it can be applied — at one point it couldn’t be applied on thead or tr, so it needs to be applied to the th directly and required position: relative to work, etc.
> It’s possible the entire <Sticky /> component can go away and be replaced with position: sticky where appropriate.
> @nickpresta

> In addition to what Nick mentioned, iirc sticky doesn't play nice with overflow because it creates a new stacking context 
> @andrewmusgrave
</details>

https://user-images.githubusercontent.com/19199063/231346811-491301cf-b2bb-4260-9094-8a40983e1f90.mp4

https://user-images.githubusercontent.com/19199063/231346466-8faef2b8-eb18-4427-85fc-96da8c86cc90.mov

**Comment by martenbjork** [comment]
Possibly related: https://github.com/Shopify/shopify/issues/417936

**Comment by alex-page** [comment]
This is the same issue @martenbjork. Should I assign @mattkubej and yourself here as well?

**Comment by sam-b-rose** [comment]
I think the issue could be related to [this line of code](https://github.com/Shopify/polaris/blob/main/polaris-react/src/utilities/sticky-manager/sticky-manager.ts#L93) in the `sticky-manager.ts`.

The `getRectForNode` function is using [`getBoundingClientRect`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) internally, which is returning the top distance of the element to the viewport.

What we want something similar to the `offsetTop` value of the container or zero if the `consainer.offsetTop` doesn't exist.

```ts
const offsetTop = this.container?.offsetTop ?? 0;
const containerTop = offsetTop + this.topBarOffset;
```

**Comment by mattkubej** [comment]
I made the proposed change that @samrose3 suggested to the [setting of containerTop with manageStickyItems](https://github.com/Shopify/polaris/blob/1cc47495a1f98e8c1a7eabec0ef0461153b33f1f/polaris-react/src/utilities/sticky-manager/sticky-manager.ts#L93) and it fixes the issue.

This [spin instance](https://admin.web.settings-sticky-table-header.matt-kubej.us.spin.dev/store/shop1/settings/custom_data) has the change written directly within the node_modules if anyone wants to play with it to verify. I have also loaded the test shop with products to validate no regressions to the Index Table.

The other uses of `getRectForNode` within that file do not seem to utilize `height` or do concern themselves with positioning in the viewport, rather than relative positioning. So, we could potentially make this change directly to `manageStickyItems`, but maybe rename `offsetTop` to `relativeOffsetTop` or `offsetTopToParent` or something along those lines to make it more clear. Alternatively, we could adjust the abstraction within `geometry` to expose this data, but I'm thinking that's probably not worth abstracting at this point and to keep it simple.

**Comment by mattkubej** [comment]
Created a [spin instance](https://admin.web.sticky-manager-offset.matt-kubej.us.spin.dev/store/shop1/settings/custom_data) with a snapshot with this [PR](https://github.com/Shopify/polaris/pull/8956).

**Comment by mattkubej** [comment]
It looks like a change might have went in that makes the metafield definitions table header no longer sticky. I'll try to find what is responsible for that change and whether this is intentional.

https://user-images.githubusercontent.com/86790511/232585404-900ed51b-5fa3-422f-9b92-200271d42317.mp4

**Comment by chloerice** [comment]
I'm guessing it was made to mitigate this bug, as the header on that table was sticking but with a gap between it and the settings modal top bar?

**Comment by mattkubej** [comment]
> I'm guessing it was made to mitigate this bug, as the header on that table was sticking but with a gap between it and the settings modal top bar?

That would be my assumption to, but I haven't find what change was responsible yet.

While I've been looking, I encountered this odd bug, which is new to me as well.

https://user-images.githubusercontent.com/86790511/232590533-a87a8b7e-da0b-409b-ba96-99a806cdf796.mp4

**Comment by mattkubej** [comment]
I found the change the resulted in the change in behavior: https://github.com/Shopify/web/pull/89581

Settings was using `<Scrollable>`, which seemed to introduce the original bug and has now been reverted. So, the most recent video is of a bug that appears to have existed with the only scrolling solution within Settings.

**Comment by mattkubej** [comment]
I think the reason the sticky behavior is no longer working with the reversion is because the SettingsBody is the scrollable container for the IndexTable. However, the StickyManager has a [scroll listener](https://github.com/Shopify/polaris/blob/91a9b77e65f565728fbfa8887dc42c0705dbb4ba/polaris-react/src/utilities/sticky-manager/sticky-manager.ts#L75) on the `container`, which is currently set to the `document`, so it is not getting fired. It looks like Scrollable adjusts the container to scroll area (i.e. itself), which is why the sticky behavior partially worked before.

I'm still trying to understand why DevTools is triggering the sticky header behavior though. It seems like there is a bug there and then there is a separate bug with Scrollabe at play.

**Comment by mattkubej** [comment]
I think I figured out why opening the DevTools triggers the StickyHeader to appear. Opening the DevTools or adjusting the dimensions of the viewport results in triggering the [handleResize](https://github.com/Shopify/polaris/blob/17e2f1328487bbb9994e7ad59260e9227234d1d5/polaris-react/src/utilities/sticky-manager/sticky-manager.ts#L37-L43) callback of the StickyManager, which invokes [manageStickyItems](https://github.com/Shopify/polaris/blob/17e2f1328487bbb9994e7ad59260e9227234d1d5/polaris-react/src/utilities/sticky-manager/sticky-manager.ts#L92-L107) and positions the sticky element. With the reversion of no longer using Scrollable, the container is the document and the offset is 56px due to the top navigation bar of the frame, so the sticky element is floating 56px from the top.

I think my proposal for how to move forward would be to introduce the necessary fixes to Polaris to accommodate the ability for Settings to use Scrollable, then reintroduce Scrollable to Settings after those fixes have made their way into web. I think the existing bug triggered due to resizing should be fixed by insuring Settings is setting the appropriate container, which Scrollable provides. What are your thoughts @chloerice and @alex-page?

**Comment by alex-page** [comment]
That makes sense to me @mattkubej. I definitely want to imagine a world where developers don't need `<Scrollable>` or `<Sticky>` but that is a totally different project. I think your proposal would be the best resolution in the short term.

**Comment by sam-b-rose** [comment]
I have tried replicating and am no longer seeing this issue. Closing out but please reopen if this issue still persists
