### ISSUE TITLE
Badge gets deformed when it becomes 2 lines due to small viewport.

### ISSUE THREAD

**Issue by nat-king** [Shopify/polaris-react#899]
# Issue summary

The badge component gets deformed when it gets broken into 2 lines.
- The line-height seems excessive.
- The width of the badge remains as it was instead of adopting the one of the text.
- The status indicator on the left is getting deformed.

<img width="370" alt="screen shot 2019-01-17 at 1 31 39 pm" src="https://user-images.githubusercontent.com/22918527/51341354-2535aa00-1a5f-11e9-81a8-40e7420807c7.png">

## Expected behavior

- The line-height should be less.
- The badge width should decrease as the width of the text does.
- The indicator on the left should remain a circle despite the accompanying text length.

## Actual behavior

As described above, the badge is getting deformed.

## Steps to reproduce the problem

1. Have the badge display more than one word.
2. Inspect the element.
3. reduce the screen size to something smaller than the badge.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number:  3.5.0
- Browser: Chrome
- Device: MacBook Pro 2015
- Operating System: Mojave

**Comment by nat-king** [comment]
This issue is also open in Web: https://github.com/Shopify/web/issues/9294 and I'm currently working on it. I will link the PR here when available.

**Comment by nat-king** [comment]
Here is the PR that was merged in the web repo to address this issue: https://github.com/Shopify/web/pull/10092

This PR didn't change the width of the badge when wrapping, only the deformation.

**Comment by ry5n** [comment]
I agree we should fix this. The linked changeset looks reasonable and I’d welcome a similar PR here. There are some things I’d change:

- Use a line height that fits the [Polaris spacing system](https://polaris.shopify.com/design/spacing#navigation): 16px rather than 15px would work
- Consider using a min-height to control the height of the element; this allows choosing an amount of vertical padding to suit the 2-line state while keeping the desired height in the 1-line state.
