### ISSUE TITLE
[ResourceList] Search and sort by <select /> are overflowing offscreen in some languages

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react#921]
# Issue summary

The `sort by` dropdown is overflowing off the page on small screens

![image](https://screenshot.click/Shop_1__Bestellungen__Shopify_2019-01-22_16-42-46.png)

Can't see inputted search text on small screens either

![image](https://screenshot.click/Shop_1__Bestellungen__Shopify_2019-01-22_16-57-16.png)

## Expected behavior

I don't have a proposed solution. I don't think truncating will work very well here i.e.:
![image](https://screenshot.click/Shop_1__Bestellungen__Shopify_2019-01-22_16-54-43.png)

This might be a good opportunity for design and content to work together on minimizing content on these rows

## Steps to reproduce the problem

1. git checkout `polaris-resource-list` in Shopify/web
1. Run server and view an orders page (orders has the necessary filters and sorty by options)
1. Shrink your screen to 

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: 3.5.0
- Browser: Chrome
- Device: Macbook Pro
- Operating System: Mojave

**Comment by ry5n** [comment]
The filtering part is being looked into now, and should improve this situation somewhat.

For the resource list header (bulk actions and sorting), truncation seems like the only thing that could be done in the component, short of a major redesign. The Polaris team might be able to tackle such a thing around Q2, but not at the moment.

In terms of content, the [resource list documentation has some suggestions for sort option microcopy](https://polaris.shopify.com/components/lists-and-tables/resource-list#study-sorting-applying). Applying those guidelines, instead of “Date (newest first)”, we might use “Most recent”. In that case, Google Translate gives me German “Neueste”. This may help.
