### ISSUE TITLE
ES Modules - esnext build directory

### ISSUE THREAD

**Issue by sdn90** [Shopify/polaris-react#925]
I'm trying to use the esnext directory and I'm running into a few issues. Is this ready for public use? Also, I'm not really sure if my intended use case matches what you guys were planning for this.

I'm just replacing my imports from `import { Card } from "@shopify/polaris" ` to `import { Card } from "@shopify/polaris/esnext"`

How I'm expecting this to work is I should be able to import components as ES Modules with Webpack out the box with no extra configuration.

1. JSX not being transpiled due to `jsx: "react-native"` preserving JSX:
https://github.com/Shopify/polaris-react/blob/f0259226ff49940885b2c49f1d7922c6d7a2c01d/tsconfig.json#L11

2. Imports to SVG files - I'm guessing these could be inlined?

3. imports to SCSS files and requires some functions from other SCSS files. 
I pull in the CSS via CDN since building it from the source has a pretty big impact on build times. The complete CSS file is 20kb minified and gzipped. Personally I'd rather take faster build times over whatever optimizations I can get building it myself.

3. Typescript definitions not declared

Example file from the esnext directory

```jsx
import * as React from 'react';
import { classNames } from '@shopify/react-utilities/styles';
import { contentContextTypes } from '../../types';
import { buttonFrom } from '../Button';
import ButtonGroup from '../ButtonGroup';
import { Header, Section } from './components';
import * as styles from './Card.scss';
export default class Card extends React.PureComponent {
    getChildContext() {
        return {
            withinContentContainer: true,
        };
    }
    render() {
        const { children, title, subdued, sectioned, actions, primaryFooterAction, secondaryFooterAction, } = this.props;
        const className = classNames(styles.Card, subdued && styles.subdued);
        const headerMarkup = title ? (<Header actions={actions} title={title}/>) : null;
        const content = sectioned ? <Section>{children}</Section> : children;
        const primaryFooterActionMarkup = primaryFooterAction
            ? buttonFrom(primaryFooterAction, { primary: true })
            : null;
        const secondaryFooterActionMarkup = secondaryFooterAction
            ? buttonFrom(secondaryFooterAction)
            : null;
        const footerMarkup = primaryFooterActionMarkup || secondaryFooterActionMarkup ? (<div className={styles.Footer}>
          <ButtonGroup>
            {secondaryFooterActionMarkup}
            {primaryFooterActionMarkup}
          </ButtonGroup>
        </div>) : null;
        return (<div className={className}>
        {headerMarkup}
        {content}
        {footerMarkup}
      </div>);
    }
}
Card.Section = Section;
Card.Header = Header;
Card.childContextTypes = contentContextTypes;
```

**Comment by BPScott** [comment]
Hi @sdn90,

The esnext folder doesn't quite do what you think it does. The good news is that getting what you want is simpler than what you're attempting.

If you're looking to use es-modules then you can `import {Card} from '@shopify/polaris'` and things will work as you intend.

We specify a [module field in our package.json](https://github.com/Shopify/polaris-react/blob/c244612b0cbf3f36f383146813507a21234b98a2/package.json#L29) which means webpack shall import form `polaris.es.js` (which exports things using the module syntax) if it encounters an import declaration. See our [webpack example folder](https://github.com/Shopify/polaris-react/tree/master/examples/webpack) for a demo of this in action. If you're using css-loader with webpack (e.g if you're using create-react-app), you can also import  `import '@shopify/polaris/styles.css';` to include our styles into your bundle instead of loading it via CDN - See our [create-react-app example](https://github.com/Shopify/polaris-react/blob/master/examples/create-react-app/src/index.js).


---

So what's the esnext folder?

The esnext folder contains a half-done build that is not publicly supported and is intended for use by internal teams only. It is compiled from typescript but with no other build steps. This is useful for us internally as apps that consume polaris can customise their browser support targets, babel configuration and some sass config overrides without tying themselves to whatever we output. This lets them fully optimize their build at the expense of requiring some more complex configuration. Eventually I'd like to work towards making this more easily consumable by external users but I'd like to do that by simplifying our what is contained within that folder to minimise complex webpack configuration rather than documenting what complexities are required currently.
