### ISSUE TITLE
[Textfield] Wrapper doesn't have an easy editable class

### ISSUE THREAD

**Issue by agustingabiola** [Shopify/polaris-react#971]
# Feature request summary

Textfield wrapper doesn't have an easy editable class.

```
            <FormLayout>

              <TextField
                value={this.state.name}
                label="Network name"
                type="text"
                autoComplete={false}
                onChange={this.valueUpdater('name')}
              />

            </FormLayout>
```
Renders to:

![image](https://user-images.githubusercontent.com/1523829/52241062-88259e80-28b1-11e9-8823-3b8112efa60b.png)

## Rationale

If the wrapper `div` has an actual class it will be easier to style the component. For example, to put the label to the left of the field

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by dpersing** [comment]
Hi @agustingabiola! Thanks for the request. We typically recommend placing the label above the field since it's easier to read across devices, but we can look into this. I'll close this issue right now since it's not on our current roadmap.

Please 👍this issue if you're looking for this feature as well, which will help us prioritize!

**Comment by agustingabiola** [comment]
I'm talking about the div with an empty class Polaris generates that wraps both the `LabelWrapper` & `TextField`
