### ISSUE TITLE
Page titleMetaData vertical alignment issue

### ISSUE THREAD

**Issue by laranoell** [Shopify/polaris-react#977]
# Issue summary

The Polaris Page Title is aligning it's child elements to the baseline, rather than the center.

## Expected behavior
<img width="388" alt="screen shot 2019-02-06 at 11 56 54 am" src="https://user-images.githubusercontent.com/3307989/52358666-6b4eaf80-2a06-11e9-8349-0b7331534b6b.png">

## Actual behavior
<img width="414" alt="screen shot 2019-02-06 at 11 56 32 am" src="https://user-images.githubusercontent.com/3307989/52358658-68ec5580-2a06-11e9-83cc-6dada8892d97.png">

## Steps to reproduce the problem

1. Render a Page component, with  `<Badge>` as the titleMetaData prop
1. Add a mock title 

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

**Comment by dpersing** [comment]
Thanks @laranoell!

@ry5n or @sarahill, any thoughts on the expected alignment for the badge?

**Comment by ry5n** [comment]
Agree we should fix this. It’s a challenge because the desired alignment depends on the content. The current alignment looks right for text content, but not for badges. Using center alignment looks right for badges but not text content.

Some possible solutions:

- Change the alignment to favor badged. If badges are the common case, this is OK.
- Add a new prop for badges or other chunky elements so these can be aligned separately from text. Downside here is people would be unable to control the order of the elements passed in.
- Add a prop that controls the alignment for everything (choose one or the other case-by-case).
- The component could wrap all the React nodes passed in, and wrap non-text nodes in a separate element with adjusted alignment (not sure this is possible).

**Comment by sarahill** [comment]
I don't know that this is possible or makes sense but could we do an `align-self: center;` on badges in this context?
