### ISSUE TITLE
[Card] Misalignment between title and action button

### ISSUE THREAD

**Issue by jim-chou-shopify** [Shopify/polaris-react#996]
# Issue summary
Title of `Card` appears to be misaligned when `Button` is a child of `Card.Header`.
```
<Card.Header title="Title">
 <Button>
</Card.Header>
```

## Expected behavior
Expect title and button to appear aligned.

## Actual behavior
<img width="659" alt="screen shot 2019-02-08 at 6 33 47 pm" src="https://user-images.githubusercontent.com/39597748/52513107-a30c5180-2bd6-11e9-91a0-8d6daf063e84.png">

## Reduced test case
https://codesandbox.io/s/zwoxr5l0xl

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number:  @shopify/polaris: 3.6.0
- Browser: Chrome
- Device: Laptop
- Operating System: Mac

**Comment by dpersing** [comment]
@ry5n and @sarahill, this issue appears to be closely aligned (pun intended) with #977.

**Comment by chloerice** [comment]
> @ry5n and @sarahill, this issue appears to be closely aligned (pun intended) with #977.

I'm not sure in this case that there's anything the component should do here. Since the header accepts a React node, I think it's up to the consumer to space the children they provide as they see fit, because the header can't anticipate what its children will be.

**Comment by ry5n** [comment]
I’m kind of surprised that `Card.Header` takes a `title` prop at all, since I assumed it was an escape hatch for taking control of the header layout. I would have expected I’d need to include my own `Heading`, which would let me control its alignment with any actions. However, even if I don’t pass a `title`, `Card.Header` renders its markup anyway (A `Stack` with an empty `Heading`).

This is maybe where we can improve things.

**Comment by chloerice** [comment]
^ This

**Comment by meandillar** [comment]
For anyone else wanting a quick fix: 
```
.Polaris-Card__Header .Polaris-Stack {
  align-items: center;
}
```
