### ISSUE TITLE
[Loading] Use Loading outside of Frame

### ISSUE THREAD

**Issue by jim-chou-shopify** [Shopify/polaris-react#997]
# Feature request summary
Expose [Loading](https://github.com/Shopify/polaris-react/tree/master/src/components/Frame/components/Loading) component to be used outside of `Frame`.

## Rationale
Marketing section has a [use case ](https://github.com/Shopify/web/pull/10467)to use `Loading` component to indicate a section of the page is loading.

![live preview](https://user-images.githubusercontent.com/39597748/52513441-d0f29580-2bd8-11e9-9866-71bbe19a7f21.gif)

@supervee 

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by dpersing** [comment]
Hi @jim-chou-shopify! Is the loading component here meant to indicate that the whole page is updating, or just a section? If it's not the whole page, the [spinner component](https://polaris.shopify.com/components/feedback-indicators/spinner) might be a better choice (and doesn't require the use of the frame component). The [loading component](https://polaris.shopify.com/components/feedback-indicators/loading#navigation) is typically meant to convey that a whole page is loading or a page-level activity is taking place, not just a section of the page.

**Comment by jim-chou-shopify** [comment]
Hi @dpersing,
I am aware of the current use case for `Loading` component.
We are wondering if it's possible to expose it for usage in individual component.
@supervee

**Comment by supervee** [comment]
Our thinking was that using this would be more effective than a spinner because:
a) it's loading an external page in a frame, it will help reinforce that the contents are from the app developer
b) because loading can happen quite often and be unpredictable in length, if a spinner were to constantly pop in and out it would be very jarring.

**Comment by dpersing** [comment]
Thanks for the extra context, @jim-chou-shopify and @supervee!

@ry5n Do you have thoughts on this?

**Comment by ry5n** [comment]
I don’t have strong feelings on this. I like the idea of emphasizing the content is from an external source, but I’m not sure the loading bar is enough for people to understand that.

@alyseadlard has done a lot of thinking about loading states, I wonder if she’d have some thoughts on the experience.

Making this available outside of the frame might take some doing. @tmlayton may have thoughts on the engineering as well as the user experience.

**Comment by jim-chou-shopify** [comment]
@ry5n I agree that ux may need further discussions but I feel the engineering aspect is straightforward by exporting `Loading` component.

**Comment by alyseadlard** [comment]
Hey all, just a couple questions:

> it's loading an external page in a frame, it will help reinforce that the contents are from the app developer

I'm not sure I understand the rationale here. Wouldn't use of `Loader` imply that it's core that's loading the content, not an app?

I might need some help understanding what `Frame` means in terms of UI. How is the content that's being loaded displayed? Is it the entire page? Is it just a modal? Is it just a section within the page?

**Comment by jim-chou-shopify** [comment]
The use case is to show a loader for preview section when fetching app generated url that is used as iframe source.
The preview is part of a form page so we do not want the loading bar to show on top of the page.

**Comment by alyseadlard** [comment]
Cool, can I get some screenshots? Not sure what "Preview section" means.

**Comment by jim-chou-shopify** [comment]
It's under Rationale section of the issue.

**Comment by alyseadlard** [comment]
Is this a card or is it a modal? Sorry, I need a bit more context.

**Comment by jim-chou-shopify** [comment]
There is also a link to the PR for our [use case ](https://github.com/Shopify/web/pull/10467).

**Comment by alyseadlard** [comment]
From a UX POV, `Loading` should only be used to indicate page level loads. Any in page loading should use either `Spinner` or skeleton loaders. It looks like this content is being loaded within the page, correct me if I'm wrong.

**Comment by jim-chou-shopify** [comment]
Yes it's part of the page.

**Comment by alyseadlard** [comment]
I'd suggest using `Spinner` or skeleton loading for your use case then.

**Comment by supervee** [comment]
Skeleton loading would not be possible as the app (could be 1P or 3P) loads the page.
We considered spinner as an option but think it is the lesser experience because:
- preview reloads every time the user changes something on the form
- preview loading time can range anywhere from immediately to several seconds

We wanted to minimize the possibility of the spinner flashing in and out when the form is changed / when the loading time is quite small

**Comment by macdonaldr93** [comment]
Just for some added information... Another reason the spinner can be a bit weird is that the preview refreshes based on the merchants interaction with the form. This isn't the best example because we've done some improvements around what event triggers the refresh, but there's a gif of typing with the spinner to refresh the preview:

![loading statae](https://user-images.githubusercontent.com/4441303/51259083-6f446000-1979-11e9-8fe1-85bb1d2f13c9.gif)

With the loading bar, it's less intrusive and the merchant would be able to see the previous preview while continuing to edit the form.

**Comment by alyseadlard** [comment]
Gotcha, thanks for the clarity @supervee @macdonaldr93! I see what you mean about both skeleton being too unpredictable and spinner being too disruptive. If it's not too much work (@tmlayton would know), let's make `Loader` available outside of the frame. This is a pretty unusual case though, so if we do this we should provide clearer documentation about do's and don'ts so that it doesn't get misused down the road. Would like to hear your thoughts on that @ry5n.

**Comment by jim-chou-shopify** [comment]
FYI, we are trying to expose [Frame/components/Loading](https://github.com/Shopify/polaris-react/tree/master/src/components/Frame/components/Loading) component to be used outside of `Frame`.

**Comment by tmlayton** [comment]
Hey everyone, sorry I missed this! What did you end up going with in the marketing section?

> @tmlayton may have thoughts on the engineering as well as the user experience.

My initial reaction on the UX is it sounds reasonable, but not enough that I would immediately commit to doing the work in Polaris.

Can we use your work in the marketing section as exploration around a section-specific loading bar? I would recommend building the component out in web in the polaris-next sub package: https://github.com/Shopify/web/tree/master/packages/%40shopify/polaris-next.

The engineering effort for this should be minimal.

**Comment by jim-chou-shopify** [comment]
Hi @tmlayton,
We have started exploring the usage of loader in the context of a loading preview for marketing activities.

https://github.com/Shopify/web/pull/12400

**Comment by tmlayton** [comment]
Looks really nice! Is this something you would have the time to contribute to Polaris?

**Comment by jim-chou-shopify** [comment]
Ya for sure.
If I can create a PR to Polaris with the loader.
